// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: packages/contracts/recordingpb/recording.proto

package recordingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrameRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	UnixNanos     int64                  `protobuf:"varint,2,opt,name=unix_nanos,json=unixNanos,proto3" json:"unix_nanos,omitempty"`
	Width         uint32                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Tiles         []*TileState           `protobuf:"bytes,5,rep,name=tiles,proto3" json:"tiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameRecord) Reset() {
	*x = FrameRecord{}
	mi := &file_packages_contracts_recordingpb_recording_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameRecord) ProtoMessage() {}

func (x *FrameRecord) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_recordingpb_recording_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameRecord.ProtoReflect.Descriptor instead.
func (*FrameRecord) Descriptor() ([]byte, []int) {
	return file_packages_contracts_recordingpb_recording_proto_rawDescGZIP(), []int{0}
}

func (x *FrameRecord) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *FrameRecord) GetUnixNanos() int64 {
	if x != nil {
		return x.UnixNanos
	}
	return 0
}

func (x *FrameRecord) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *FrameRecord) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FrameRecord) GetTiles() []*TileState {
	if x != nil {
		return x.Tiles
	}
	return nil
}

type TileState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             uint32                 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint32                 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	R             uint32                 `protobuf:"varint,3,opt,name=r,proto3" json:"r,omitempty"`
	G             uint32                 `protobuf:"varint,4,opt,name=g,proto3" json:"g,omitempty"`
	B             uint32                 `protobuf:"varint,5,opt,name=b,proto3" json:"b,omitempty"`
	Pressed       bool                   `protobuf:"varint,6,opt,name=pressed,proto3" json:"pressed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TileState) Reset() {
	*x = TileState{}
	mi := &file_packages_contracts_recordingpb_recording_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TileState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TileState) ProtoMessage() {}

func (x *TileState) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_recordingpb_recording_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TileState.ProtoReflect.Descriptor instead.
func (*TileState) Descriptor() ([]byte, []int) {
	return file_packages_contracts_recordingpb_recording_proto_rawDescGZIP(), []int{1}
}

func (x *TileState) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TileState) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *TileState) GetR() uint32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *TileState) GetG() uint32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *TileState) GetB() uint32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *TileState) GetPressed() bool {
	if x != nil {
		return x.Pressed
	}
	return false
}

var File_packages_contracts_recordingpb_recording_proto protoreflect.FileDescriptor

const file_packages_contracts_recordingpb_recording_proto_rawDesc = "" +
	"\n" +
	".packages/contracts/recordingpb/recording.proto\x12 motionlevels.engine.recording.v1\"\xb9\x01\n" +
	"\vFrameRecord\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x1d\n" +
	"\n" +
	"unix_nanos\x18\x02 \x01(\x03R\tunixNanos\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\rR\x06height\x12A\n" +
	"\x05tiles\x18\x05 \x03(\v2+.motionlevels.engine.recording.v1.TileStateR\x05tiles\"k\n" +
	"\tTileState\x12\f\n" +
	"\x01x\x18\x01 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\rR\x01y\x12\f\n" +
	"\x01r\x18\x03 \x01(\rR\x01r\x12\f\n" +
	"\x01g\x18\x04 \x01(\rR\x01g\x12\f\n" +
	"\x01b\x18\x05 \x01(\rR\x01b\x12\x18\n" +
	"\apressed\x18\x06 \x01(\bR\apressedB?Z=github.com/lobis/motion-levels/packages/contracts/recordingpbb\x06proto3"

var (
	file_packages_contracts_recordingpb_recording_proto_rawDescOnce sync.Once
	file_packages_contracts_recordingpb_recording_proto_rawDescData []byte
)

func file_packages_contracts_recordingpb_recording_proto_rawDescGZIP() []byte {
	file_packages_contracts_recordingpb_recording_proto_rawDescOnce.Do(func() {
		file_packages_contracts_recordingpb_recording_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_contracts_recordingpb_recording_proto_rawDesc), len(file_packages_contracts_recordingpb_recording_proto_rawDesc)))
	})
	return file_packages_contracts_recordingpb_recording_proto_rawDescData
}

var file_packages_contracts_recordingpb_recording_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_packages_contracts_recordingpb_recording_proto_goTypes = []any{
	(*FrameRecord)(nil), // 0: motionlevels.engine.recording.v1.FrameRecord
	(*TileState)(nil),   // 1: motionlevels.engine.recording.v1.TileState
}
var file_packages_contracts_recordingpb_recording_proto_depIdxs = []int32{
	1, // 0: motionlevels.engine.recording.v1.FrameRecord.tiles:type_name -> motionlevels.engine.recording.v1.TileState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_packages_contracts_recordingpb_recording_proto_init() }
func file_packages_contracts_recordingpb_recording_proto_init() {
	if File_packages_contracts_recordingpb_recording_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_contracts_recordingpb_recording_proto_rawDesc), len(file_packages_contracts_recordingpb_recording_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packages_contracts_recordingpb_recording_proto_goTypes,
		DependencyIndexes: file_packages_contracts_recordingpb_recording_proto_depIdxs,
		MessageInfos:      file_packages_contracts_recordingpb_recording_proto_msgTypes,
	}.Build()
	File_packages_contracts_recordingpb_recording_proto = out.File
	file_packages_contracts_recordingpb_recording_proto_goTypes = nil
	file_packages_contracts_recordingpb_recording_proto_depIdxs = nil
}
