// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: packages/contracts/floorpb/floor.proto

package floorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_EngineHello
	//	*Envelope_AdapterHello
	//	*Envelope_DesiredFrame
	//	*Envelope_PressureEvent
	//	*Envelope_PresentedFrame
	//	*Envelope_AdapterStatus
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_packages_contracts_floorpb_floor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_floorpb_floor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_packages_contracts_floorpb_floor_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetEngineHello() *EngineHello {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_EngineHello); ok {
			return x.EngineHello
		}
	}
	return nil
}

func (x *Envelope) GetAdapterHello() *AdapterHello {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AdapterHello); ok {
			return x.AdapterHello
		}
	}
	return nil
}

func (x *Envelope) GetDesiredFrame() *DesiredFrame {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_DesiredFrame); ok {
			return x.DesiredFrame
		}
	}
	return nil
}

func (x *Envelope) GetPressureEvent() *PressureEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PressureEvent); ok {
			return x.PressureEvent
		}
	}
	return nil
}

func (x *Envelope) GetPresentedFrame() *PresentedFrame {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PresentedFrame); ok {
			return x.PresentedFrame
		}
	}
	return nil
}

func (x *Envelope) GetAdapterStatus() *AdapterStatus {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AdapterStatus); ok {
			return x.AdapterStatus
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_EngineHello struct {
	EngineHello *EngineHello `protobuf:"bytes,1,opt,name=engine_hello,json=engineHello,proto3,oneof"`
}

type Envelope_AdapterHello struct {
	AdapterHello *AdapterHello `protobuf:"bytes,2,opt,name=adapter_hello,json=adapterHello,proto3,oneof"`
}

type Envelope_DesiredFrame struct {
	DesiredFrame *DesiredFrame `protobuf:"bytes,3,opt,name=desired_frame,json=desiredFrame,proto3,oneof"`
}

type Envelope_PressureEvent struct {
	PressureEvent *PressureEvent `protobuf:"bytes,4,opt,name=pressure_event,json=pressureEvent,proto3,oneof"`
}

type Envelope_PresentedFrame struct {
	PresentedFrame *PresentedFrame `protobuf:"bytes,5,opt,name=presented_frame,json=presentedFrame,proto3,oneof"`
}

type Envelope_AdapterStatus struct {
	AdapterStatus *AdapterStatus `protobuf:"bytes,6,opt,name=adapter_status,json=adapterStatus,proto3,oneof"`
}

func (*Envelope_EngineHello) isEnvelope_Payload() {}

func (*Envelope_AdapterHello) isEnvelope_Payload() {}

func (*Envelope_DesiredFrame) isEnvelope_Payload() {}

func (*Envelope_PressureEvent) isEnvelope_Payload() {}

func (*Envelope_PresentedFrame) isEnvelope_Payload() {}

func (*Envelope_AdapterStatus) isEnvelope_Payload() {}

type EngineHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	EngineRevision  string                 `protobuf:"bytes,2,opt,name=engine_revision,json=engineRevision,proto3" json:"engine_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EngineHello) Reset() {
	*x = EngineHello{}
	mi := &file_packages_contracts_floorpb_floor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineHello) ProtoMessage() {}

func (x *EngineHello) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_floorpb_floor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineHello.ProtoReflect.Descriptor instead.
func (*EngineHello) Descriptor() ([]byte, []int) {
	return file_packages_contracts_floorpb_floor_proto_rawDescGZIP(), []int{1}
}

func (x *EngineHello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *EngineHello) GetEngineRevision() string {
	if x != nil {
		return x.EngineRevision
	}
	return ""
}

type AdapterHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	AdapterRevision string                 `protobuf:"bytes,2,opt,name=adapter_revision,json=adapterRevision,proto3" json:"adapter_revision,omitempty"`
	Width           uint32                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height          uint32                 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	TargetFps       uint32                 `protobuf:"varint,5,opt,name=target_fps,json=targetFps,proto3" json:"target_fps,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdapterHello) Reset() {
	*x = AdapterHello{}
	mi := &file_packages_contracts_floorpb_floor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterHello) ProtoMessage() {}

func (x *AdapterHello) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_floorpb_floor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterHello.ProtoReflect.Descriptor instead.
func (*AdapterHello) Descriptor() ([]byte, []int) {
	return file_packages_contracts_floorpb_floor_proto_rawDescGZIP(), []int{2}
}

func (x *AdapterHello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *AdapterHello) GetAdapterRevision() string {
	if x != nil {
		return x.AdapterRevision
	}
	return ""
}

func (x *AdapterHello) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *AdapterHello) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *AdapterHello) GetTargetFps() uint32 {
	if x != nil {
		return x.TargetFps
	}
	return 0
}

type DesiredFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	UnixNanos     int64                  `protobuf:"varint,2,opt,name=unix_nanos,json=unixNanos,proto3" json:"unix_nanos,omitempty"`
	Width         uint32                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Rgb           []byte                 `protobuf:"bytes,5,opt,name=rgb,proto3" json:"rgb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesiredFrame) Reset() {
	*x = DesiredFrame{}
	mi := &file_packages_contracts_floorpb_floor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredFrame) ProtoMessage() {}

func (x *DesiredFrame) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_floorpb_floor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredFrame.ProtoReflect.Descriptor instead.
func (*DesiredFrame) Descriptor() ([]byte, []int) {
	return file_packages_contracts_floorpb_floor_proto_rawDescGZIP(), []int{3}
}

func (x *DesiredFrame) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *DesiredFrame) GetUnixNanos() int64 {
	if x != nil {
		return x.UnixNanos
	}
	return 0
}

func (x *DesiredFrame) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *DesiredFrame) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *DesiredFrame) GetRgb() []byte {
	if x != nil {
		return x.Rgb
	}
	return nil
}

type PressureEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Sequence           uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	UnixNanos          int64                  `protobuf:"varint,2,opt,name=unix_nanos,json=unixNanos,proto3" json:"unix_nanos,omitempty"`
	X                  uint32                 `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                  uint32                 `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Pressed            bool                   `protobuf:"varint,5,opt,name=pressed,proto3" json:"pressed,omitempty"`
	HardwareController uint32                 `protobuf:"varint,6,opt,name=hardware_controller,json=hardwareController,proto3" json:"hardware_controller,omitempty"`
	HardwareChannel    uint32                 `protobuf:"varint,7,opt,name=hardware_channel,json=hardwareChannel,proto3" json:"hardware_channel,omitempty"`
	HardwarePosition   uint32                 `protobuf:"varint,8,opt,name=hardware_position,json=hardwarePosition,proto3" json:"hardware_position,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PressureEvent) Reset() {
	*x = PressureEvent{}
	mi := &file_packages_contracts_floorpb_floor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PressureEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PressureEvent) ProtoMessage() {}

func (x *PressureEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_floorpb_floor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PressureEvent.ProtoReflect.Descriptor instead.
func (*PressureEvent) Descriptor() ([]byte, []int) {
	return file_packages_contracts_floorpb_floor_proto_rawDescGZIP(), []int{4}
}

func (x *PressureEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PressureEvent) GetUnixNanos() int64 {
	if x != nil {
		return x.UnixNanos
	}
	return 0
}

func (x *PressureEvent) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PressureEvent) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PressureEvent) GetPressed() bool {
	if x != nil {
		return x.Pressed
	}
	return false
}

func (x *PressureEvent) GetHardwareController() uint32 {
	if x != nil {
		return x.HardwareController
	}
	return 0
}

func (x *PressureEvent) GetHardwareChannel() uint32 {
	if x != nil {
		return x.HardwareChannel
	}
	return 0
}

func (x *PressureEvent) GetHardwarePosition() uint32 {
	if x != nil {
		return x.HardwarePosition
	}
	return 0
}

type PresentedFrame struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PresentationSequence uint64                 `protobuf:"varint,1,opt,name=presentation_sequence,json=presentationSequence,proto3" json:"presentation_sequence,omitempty"`
	DesiredSequence      uint64                 `protobuf:"varint,2,opt,name=desired_sequence,json=desiredSequence,proto3" json:"desired_sequence,omitempty"`
	PresentedUnixNanos   int64                  `protobuf:"varint,3,opt,name=presented_unix_nanos,json=presentedUnixNanos,proto3" json:"presented_unix_nanos,omitempty"`
	Width                uint32                 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32                 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Rgb                  []byte                 `protobuf:"bytes,6,opt,name=rgb,proto3" json:"rgb,omitempty"`
	PressureBits         []byte                 `protobuf:"bytes,7,opt,name=pressure_bits,json=pressureBits,proto3" json:"pressure_bits,omitempty"`
	FadeRatio            float32                `protobuf:"fixed32,8,opt,name=fade_ratio,json=fadeRatio,proto3" json:"fade_ratio,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PresentedFrame) Reset() {
	*x = PresentedFrame{}
	mi := &file_packages_contracts_floorpb_floor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresentedFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresentedFrame) ProtoMessage() {}

func (x *PresentedFrame) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_floorpb_floor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresentedFrame.ProtoReflect.Descriptor instead.
func (*PresentedFrame) Descriptor() ([]byte, []int) {
	return file_packages_contracts_floorpb_floor_proto_rawDescGZIP(), []int{5}
}

func (x *PresentedFrame) GetPresentationSequence() uint64 {
	if x != nil {
		return x.PresentationSequence
	}
	return 0
}

func (x *PresentedFrame) GetDesiredSequence() uint64 {
	if x != nil {
		return x.DesiredSequence
	}
	return 0
}

func (x *PresentedFrame) GetPresentedUnixNanos() int64 {
	if x != nil {
		return x.PresentedUnixNanos
	}
	return 0
}

func (x *PresentedFrame) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *PresentedFrame) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PresentedFrame) GetRgb() []byte {
	if x != nil {
		return x.Rgb
	}
	return nil
}

func (x *PresentedFrame) GetPressureBits() []byte {
	if x != nil {
		return x.PressureBits
	}
	return nil
}

func (x *PresentedFrame) GetFadeRatio() float32 {
	if x != nil {
		return x.FadeRatio
	}
	return 0
}

type AdapterStatus struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UnixNanos             int64                  `protobuf:"varint,1,opt,name=unix_nanos,json=unixNanos,proto3" json:"unix_nanos,omitempty"`
	PresentedFrames       uint64                 `protobuf:"varint,2,opt,name=presented_frames,json=presentedFrames,proto3" json:"presented_frames,omitempty"`
	ActualFps             float64                `protobuf:"fixed64,3,opt,name=actual_fps,json=actualFps,proto3" json:"actual_fps,omitempty"`
	TargetFps             uint32                 `protobuf:"varint,4,opt,name=target_fps,json=targetFps,proto3" json:"target_fps,omitempty"`
	DesiredFrameAgeMillis int64                  `protobuf:"varint,5,opt,name=desired_frame_age_millis,json=desiredFrameAgeMillis,proto3" json:"desired_frame_age_millis,omitempty"`
	UdpSendErrors         uint64                 `protobuf:"varint,6,opt,name=udp_send_errors,json=udpSendErrors,proto3" json:"udp_send_errors,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AdapterStatus) Reset() {
	*x = AdapterStatus{}
	mi := &file_packages_contracts_floorpb_floor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterStatus) ProtoMessage() {}

func (x *AdapterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_floorpb_floor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterStatus.ProtoReflect.Descriptor instead.
func (*AdapterStatus) Descriptor() ([]byte, []int) {
	return file_packages_contracts_floorpb_floor_proto_rawDescGZIP(), []int{6}
}

func (x *AdapterStatus) GetUnixNanos() int64 {
	if x != nil {
		return x.UnixNanos
	}
	return 0
}

func (x *AdapterStatus) GetPresentedFrames() uint64 {
	if x != nil {
		return x.PresentedFrames
	}
	return 0
}

func (x *AdapterStatus) GetActualFps() float64 {
	if x != nil {
		return x.ActualFps
	}
	return 0
}

func (x *AdapterStatus) GetTargetFps() uint32 {
	if x != nil {
		return x.TargetFps
	}
	return 0
}

func (x *AdapterStatus) GetDesiredFrameAgeMillis() int64 {
	if x != nil {
		return x.DesiredFrameAgeMillis
	}
	return 0
}

func (x *AdapterStatus) GetUdpSendErrors() uint64 {
	if x != nil {
		return x.UdpSendErrors
	}
	return 0
}

var File_packages_contracts_floorpb_floor_proto protoreflect.FileDescriptor

const file_packages_contracts_floorpb_floor_proto_rawDesc = "" +
	"\n" +
	"&packages/contracts/floorpb/floor.proto\x12\x15motionlevels.floor.v2\"\xe6\x03\n" +
	"\bEnvelope\x12G\n" +
	"\fengine_hello\x18\x01 \x01(\v2\".motionlevels.floor.v2.EngineHelloH\x00R\vengineHello\x12J\n" +
	"\radapter_hello\x18\x02 \x01(\v2#.motionlevels.floor.v2.AdapterHelloH\x00R\fadapterHello\x12J\n" +
	"\rdesired_frame\x18\x03 \x01(\v2#.motionlevels.floor.v2.DesiredFrameH\x00R\fdesiredFrame\x12M\n" +
	"\x0epressure_event\x18\x04 \x01(\v2$.motionlevels.floor.v2.PressureEventH\x00R\rpressureEvent\x12P\n" +
	"\x0fpresented_frame\x18\x05 \x01(\v2%.motionlevels.floor.v2.PresentedFrameH\x00R\x0epresentedFrame\x12M\n" +
	"\x0eadapter_status\x18\x06 \x01(\v2$.motionlevels.floor.v2.AdapterStatusH\x00R\radapterStatusB\t\n" +
	"\apayload\"a\n" +
	"\vEngineHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12'\n" +
	"\x0fengine_revision\x18\x02 \x01(\tR\x0eengineRevision\"\xb1\x01\n" +
	"\fAdapterHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12)\n" +
	"\x10adapter_revision\x18\x02 \x01(\tR\x0fadapterRevision\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\rR\x06height\x12\x1d\n" +
	"\n" +
	"target_fps\x18\x05 \x01(\rR\ttargetFps\"\x89\x01\n" +
	"\fDesiredFrame\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x1d\n" +
	"\n" +
	"unix_nanos\x18\x02 \x01(\x03R\tunixNanos\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\rR\x06height\x12\x10\n" +
	"\x03rgb\x18\x05 \x01(\fR\x03rgb\"\x89\x02\n" +
	"\rPressureEvent\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x1d\n" +
	"\n" +
	"unix_nanos\x18\x02 \x01(\x03R\tunixNanos\x12\f\n" +
	"\x01x\x18\x03 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\rR\x01y\x12\x18\n" +
	"\apressed\x18\x05 \x01(\bR\apressed\x12/\n" +
	"\x13hardware_controller\x18\x06 \x01(\rR\x12hardwareController\x12)\n" +
	"\x10hardware_channel\x18\a \x01(\rR\x0fhardwareChannel\x12+\n" +
	"\x11hardware_position\x18\b \x01(\rR\x10hardwarePosition\"\xa6\x02\n" +
	"\x0ePresentedFrame\x123\n" +
	"\x15presentation_sequence\x18\x01 \x01(\x04R\x14presentationSequence\x12)\n" +
	"\x10desired_sequence\x18\x02 \x01(\x04R\x0fdesiredSequence\x120\n" +
	"\x14presented_unix_nanos\x18\x03 \x01(\x03R\x12presentedUnixNanos\x12\x14\n" +
	"\x05width\x18\x04 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\rR\x06height\x12\x10\n" +
	"\x03rgb\x18\x06 \x01(\fR\x03rgb\x12#\n" +
	"\rpressure_bits\x18\a \x01(\fR\fpressureBits\x12\x1d\n" +
	"\n" +
	"fade_ratio\x18\b \x01(\x02R\tfadeRatio\"\xf8\x01\n" +
	"\rAdapterStatus\x12\x1d\n" +
	"\n" +
	"unix_nanos\x18\x01 \x01(\x03R\tunixNanos\x12)\n" +
	"\x10presented_frames\x18\x02 \x01(\x04R\x0fpresentedFrames\x12\x1d\n" +
	"\n" +
	"actual_fps\x18\x03 \x01(\x01R\tactualFps\x12\x1d\n" +
	"\n" +
	"target_fps\x18\x04 \x01(\rR\ttargetFps\x127\n" +
	"\x18desired_frame_age_millis\x18\x05 \x01(\x03R\x15desiredFrameAgeMillis\x12&\n" +
	"\x0fudp_send_errors\x18\x06 \x01(\x04R\rudpSendErrorsB;Z9github.com/lobis/motion-levels/packages/contracts/floorpbb\x06proto3"

var (
	file_packages_contracts_floorpb_floor_proto_rawDescOnce sync.Once
	file_packages_contracts_floorpb_floor_proto_rawDescData []byte
)

func file_packages_contracts_floorpb_floor_proto_rawDescGZIP() []byte {
	file_packages_contracts_floorpb_floor_proto_rawDescOnce.Do(func() {
		file_packages_contracts_floorpb_floor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_contracts_floorpb_floor_proto_rawDesc), len(file_packages_contracts_floorpb_floor_proto_rawDesc)))
	})
	return file_packages_contracts_floorpb_floor_proto_rawDescData
}

var file_packages_contracts_floorpb_floor_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_packages_contracts_floorpb_floor_proto_goTypes = []any{
	(*Envelope)(nil),       // 0: motionlevels.floor.v2.Envelope
	(*EngineHello)(nil),    // 1: motionlevels.floor.v2.EngineHello
	(*AdapterHello)(nil),   // 2: motionlevels.floor.v2.AdapterHello
	(*DesiredFrame)(nil),   // 3: motionlevels.floor.v2.DesiredFrame
	(*PressureEvent)(nil),  // 4: motionlevels.floor.v2.PressureEvent
	(*PresentedFrame)(nil), // 5: motionlevels.floor.v2.PresentedFrame
	(*AdapterStatus)(nil),  // 6: motionlevels.floor.v2.AdapterStatus
}
var file_packages_contracts_floorpb_floor_proto_depIdxs = []int32{
	1, // 0: motionlevels.floor.v2.Envelope.engine_hello:type_name -> motionlevels.floor.v2.EngineHello
	2, // 1: motionlevels.floor.v2.Envelope.adapter_hello:type_name -> motionlevels.floor.v2.AdapterHello
	3, // 2: motionlevels.floor.v2.Envelope.desired_frame:type_name -> motionlevels.floor.v2.DesiredFrame
	4, // 3: motionlevels.floor.v2.Envelope.pressure_event:type_name -> motionlevels.floor.v2.PressureEvent
	5, // 4: motionlevels.floor.v2.Envelope.presented_frame:type_name -> motionlevels.floor.v2.PresentedFrame
	6, // 5: motionlevels.floor.v2.Envelope.adapter_status:type_name -> motionlevels.floor.v2.AdapterStatus
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_packages_contracts_floorpb_floor_proto_init() }
func file_packages_contracts_floorpb_floor_proto_init() {
	if File_packages_contracts_floorpb_floor_proto != nil {
		return
	}
	file_packages_contracts_floorpb_floor_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_EngineHello)(nil),
		(*Envelope_AdapterHello)(nil),
		(*Envelope_DesiredFrame)(nil),
		(*Envelope_PressureEvent)(nil),
		(*Envelope_PresentedFrame)(nil),
		(*Envelope_AdapterStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_contracts_floorpb_floor_proto_rawDesc), len(file_packages_contracts_floorpb_floor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packages_contracts_floorpb_floor_proto_goTypes,
		DependencyIndexes: file_packages_contracts_floorpb_floor_proto_depIdxs,
		MessageInfos:      file_packages_contracts_floorpb_floor_proto_msgTypes,
	}.Build()
	File_packages_contracts_floorpb_floor_proto = out.File
	file_packages_contracts_floorpb_floor_proto_goTypes = nil
	file_packages_contracts_floorpb_floor_proto_depIdxs = nil
}
