// Code generated by 'make motion-go-seeds' from game-engine/internal/games/authored/nativegames/duelgo/game.go. DO NOT EDIT.
export const duelMotionGoSource = String.raw`// Code generated from game-engine/internal/games/authored/nativegames/duelgo/game.go; edit the engine copy and run 'make motion-go-seeds'.
package main

import (
	"math"

	"github.com/lobis/motion-levels/packages/motiongo"
)

const (
	startPadSize     = 4
	setupDurationNS  = int64(3000000000)
	setupBlinks      = 3
	startPadHoldNS   = int64(1000000000)
	claimFlashNS     = int64(240000000)
	maxDuelPlayers   = 8
	minDuelPlayers   = 2
	boardCandidateN  = 18
	mediumFillPct    = 60
	hardFillPct      = 90
	defaultFillPct   = mediumFillPct
	boardTileCount   = motiongo.Width * motiongo.Height
	DefaultMusicRef  = "Motion/canciones/Musica8.mp3"
	DefaultMusicGain = 14
)

type point struct {
	x int
	y int
}

type rgb struct {
	r int
	g int
	b int
}

type playerState struct {
	label string
	color rgb
	score int
}

var defaultPlayers = [maxDuelPlayers]motiongo.Player{
	{Index: 0, Label: "Red", Color: "#ff0000"},
	{Index: 1, Label: "Cyan", Color: "#00ffff"},
	{Index: 2, Label: "Green", Color: "#00ff00"},
	{Index: 3, Label: "Pink", Color: "#ff00ff"},
	{Index: 4, Label: "Blue", Color: "#0000ff"},
	{Index: 5, Label: "Yellow", Color: "#ffff00"},
	{Index: 6, Label: "Violet", Color: "#a78bfa"},
	{Index: 7, Label: "Orange", Color: "#fb923c"},
}

var players []motiongo.Player
var playerCount int
var playerStates [maxDuelPlayers]playerState
var owners [boardTileCount]int
var claimed [boardTileCount]bool
var claimedAt [boardTileCount]int64
var tilesPerPlayer int
var targetTiles [maxDuelPlayers]int
var fillPercent int
var startPadPresses [maxDuelPlayers]uint16
var startPadHold [maxDuelPlayers]int64
var startPadOrigin [maxDuelPlayers]point
var setupStartedNS int64
var setupUntilNS int64
var startedNS int64
var endedNS int64
var winner int
var rng uint32

//export alloc
func gameAlloc(size uint32) uint32 {
	return motiongo.Alloc(size)
}

//export init
func gameInit(ptr uint32, length uint32) uint64 {
	var req motiongo.InitRequest
	_ = motiongo.Decode(ptr, length, &req)
	players = normalizePlayers(req.Players)
	playerCount = len(players)
	fillPercent = difficultyFillPercent(req.Difficulty)
	rng = uint32(req.Seed)
	if rng == 0 {
		rng = uint32(req.NowUnixNS)
	}
	setupStartedNS = 0
	setupUntilNS = 0
	startedNS = 0
	endedNS = 0
	winner = -1
	for i := 0; i < maxDuelPlayers; i++ {
		startPadPresses[i] = 0
		startPadHold[i] = 0
		playerStates[i] = playerState{}
		targetTiles[i] = 0
	}
	for i := 0; i < boardTileCount; i++ {
		owners[i] = -1
		claimed[i] = false
		claimedAt[i] = 0
	}
	assignStartPadOrigins()
	for i := 0; i < playerCount; i++ {
		playerStates[i] = playerState{
			label: players[i].Label,
			color: parseColor(players[i].Color, parseColor(defaultPlayers[i].Color, rgb{255, 255, 255})),
		}
	}
	generateBoard()
	return motiongo.Respond([]motiongo.Event{{Cue: "start", Message: "Duelo listo"}})
}

//export press
func gamePress(ptr uint32, length uint32) uint64 {
	var req motiongo.PressRequest
	_ = motiongo.Decode(ptr, length, &req)
	if !inBounds(req.X, req.Y) {
		return motiongo.Respond([]motiongo.Event{})
	}
	pt := point{x: req.X, y: req.Y}
	if winner >= 0 {
		return motiongo.Respond([]motiongo.Event{})
	}
	if awaitingPlayers() || inSetup(req.NowUnixNS) {
		wasAwaiting := awaitingPlayers()
		handleStartPadPress(pt, req.Pressed, req.NowUnixNS)
		if req.Pressed && wasAwaiting && !awaitingPlayers() {
			return motiongo.Respond([]motiongo.Event{{Cue: "start", Message: "duel starting"}})
		}
		return motiongo.Respond([]motiongo.Event{})
	}
	if !req.Pressed {
		return motiongo.Respond([]motiongo.Event{})
	}
	index := tileIndex(pt)
	player := owners[index]
	if player < 0 || player >= playerCount || claimed[index] {
		return motiongo.Respond([]motiongo.Event{})
	}
	claimed[index] = true
	claimedAt[index] = req.NowUnixNS
	playerStates[player].score++
	if playerStates[player].score >= targetTiles[player] {
		winner = player
		endedNS = req.NowUnixNS
		return motiongo.Respond([]motiongo.Event{{Cue: "win", Message: playerLabel(player) + " gana"}})
	}
	return motiongo.Respond([]motiongo.Event{{Cue: "coin", Message: playerLabel(player) + " " + itoa(playerStates[player].score)}})
}

//export tick
func gameTick(ptr uint32, length uint32) uint64 {
	return 0
}

//export render
func gameRender(ptr uint32, length uint32) uint64 {
	var req motiongo.TimeRequest
	_ = motiongo.Decode(ptr, length, &req)
	frame := motiongo.NewFrame(motiongo.Black)
	for y := 0; y < motiongo.Height; y++ {
		for x := 0; x < motiongo.Width; x++ {
			frame.Set(x, y, rgbColor(colorAt(point{x: x, y: y}, req.NowUnixNS)))
		}
	}
	return motiongo.Respond(frame)
}

//export snapshot
func gameSnapshot(ptr uint32, length uint32) uint64 {
	var req motiongo.TimeRequest
	_ = motiongo.Decode(ptr, length, &req)
	phase := "running"
	if awaitingPlayers() {
		phase = "ready"
	} else if inSetup(req.NowUnixNS) {
		phase = "countdown"
	} else if winner >= 0 {
		phase = "finished"
	}
	bestScore := 0
	snapPlayers := make([]motiongo.PlayerSnapshot, 0, playerCount)
	for i := 0; i < playerCount; i++ {
		score := playerStates[i].score
		if score > bestScore {
			bestScore = score
		}
		snapPlayers = append(snapPlayers, motiongo.PlayerSnapshot{
			Index: i,
			Label: playerLabel(i),
			Color: rgbHex(playerStates[i].color),
			Score: score,
			Lives: -1,
		})
	}
	elapsed := int64(0)
	if startedNS > 0 && req.NowUnixNS > startedNS {
		endNS := req.NowUnixNS
		if endedNS > 0 {
			endNS = endedNS
		}
		elapsed = (endNS - startedNS) / 1000000
	}
	countdown := int64(0)
	if inSetup(req.NowUnixNS) {
		countdown = (setupUntilNS - req.NowUnixNS) / 1000000
	}
	return motiongo.Respond(motiongo.Snapshot{
		Phase:           phase,
		Players:         snapPlayers,
		Score:           bestScore,
		StartedUnix:     startedNS / 1000000000,
		ElapsedMillis:   elapsed,
		CountdownMillis: countdown,
		ActiveTargets:   remainingTargets(),
		Lives:           -1,
		Success:         winner >= 0,
	})
}

func colorAt(pt point, nowNS int64) rgb {
	if awaitingPlayers() || inSetup(nowNS) {
		return startPadColor(pt, nowNS)
	}
	if winner >= 0 {
		return winnerColor(playerStates[winner].color, pt, nowNS, endedNS)
	}
	index := tileIndex(pt)
	player := owners[index]
	if player < 0 || player >= playerCount {
		return rgb{}
	}
	base := playerStates[player].color
	if claimed[index] {
		if claimedAt[index] > 0 && nowNS-claimedAt[index] < claimFlashNS {
			return rgb{255, 255, 255}
		}
		return scaleRGB(base, 0.16)
	}
	pulse := 0.78 + 0.22*math.Sin(float64(nowNS)/1000000000*2.2+float64(pt.x*3+pt.y)*0.08)
	return scaleRGB(base, pulse)
}

func generateBoard() {
	totalTargets := (boardTileCount*fillPercent + 50) / 100
	tilesPerPlayer = maxInt(1, totalTargets/playerCount)
	targets := [maxDuelPlayers]int{}
	for player := 0; player < playerCount; player++ {
		targets[player] = tilesPerPlayer
		if player < totalTargets%playerCount {
			targets[player]++
		}
		targetTiles[player] = targets[player]
	}
	best := [boardTileCount]int{}
	bestScore := math.Inf(1)
	for attempt := 0; attempt < boardCandidateN; attempt++ {
		candidate := generateBoardCandidate(targets)
		score := boardOrganicPenalty(candidate)
		if score < bestScore {
			bestScore = score
			best = candidate
		}
	}
	owners = best
}

func generateBoardCandidate(targets [maxDuelPlayers]int) [boardTileCount]int {
	var candidate [boardTileCount]int
	var order [boardTileCount]int
	var counts [maxDuelPlayers]int
	for i := 0; i < boardTileCount; i++ {
		candidate[i] = -1
		order[i] = i
	}
	shuffleOrder(&order)
	for orderIndex := 0; orderIndex < boardTileCount; orderIndex++ {
		index := order[orderIndex]
		bestPlayer := -1
		bestScore := math.Inf(1)
		x := index % motiongo.Width
		y := index / motiongo.Width
		for player := 0; player < playerCount; player++ {
			target := targets[player]
			if counts[player] >= target {
				continue
			}
			sameOrth := sameOrthogonalNeighbors(candidate, x, y, player)
			sameDiag := sameDiagonalNeighbors(candidate, x, y, player)
			score := localAdjacencyPenalty(sameOrth)
			score += float64(sameDiag) * 0.12
			score += float64(counts[player]) / float64(target) * 0.2
			score += nextFloat() * 1.35
			if score < bestScore {
				bestScore = score
				bestPlayer = player
			}
		}
		if bestPlayer < 0 {
			continue
		}
		candidate[index] = bestPlayer
		counts[bestPlayer]++
	}
	return candidate
}

func shuffleOrder(order *[boardTileCount]int) {
	for i := boardTileCount - 1; i > 0; i-- {
		j := int(nextRand() % uint32(i+1))
		order[i], order[j] = order[j], order[i]
	}
}

func localAdjacencyPenalty(sameOrth int) float64 {
	switch sameOrth {
	case 0:
		return 0.85
	case 1:
		return 0
	case 2:
		return 0.45
	default:
		return 4.5
	}
}

func boardOrganicPenalty(board [boardTileCount]int) float64 {
	penalty := 0.0
	for y := 0; y < motiongo.Height; y++ {
		runOwner := -2
		runLength := 0
		for x := 0; x < motiongo.Width; x++ {
			owner := board[y*motiongo.Width+x]
			if owner >= 0 {
				sameOrth := sameOrthogonalNeighbors(board, x, y, owner)
				penalty += localAdjacencyPenalty(sameOrth)
				if sameOrth >= 3 {
					penalty += 6
				}
			}
			if owner == runOwner && owner >= 0 {
				runLength++
			} else {
				runOwner = owner
				runLength = 1
			}
			if runOwner >= 0 && runLength > 5 {
				penalty += float64(runLength-5) * 7
			}
		}
	}
	for x := 0; x < motiongo.Width; x++ {
		runOwner := -2
		runLength := 0
		for y := 0; y < motiongo.Height; y++ {
			owner := board[y*motiongo.Width+x]
			if owner == runOwner && owner >= 0 {
				runLength++
			} else {
				runOwner = owner
				runLength = 1
			}
			if runOwner >= 0 && runLength > 5 {
				penalty += float64(runLength-5) * 7
			}
		}
	}
	return penalty
}

func sameOrthogonalNeighbors(board [boardTileCount]int, x int, y int, player int) int {
	count := 0
	if x > 0 && board[y*motiongo.Width+x-1] == player {
		count++
	}
	if x < motiongo.Width-1 && board[y*motiongo.Width+x+1] == player {
		count++
	}
	if y > 0 && board[(y-1)*motiongo.Width+x] == player {
		count++
	}
	if y < motiongo.Height-1 && board[(y+1)*motiongo.Width+x] == player {
		count++
	}
	return count
}

func sameDiagonalNeighbors(board [boardTileCount]int, x int, y int, player int) int {
	count := 0
	if x > 0 && y > 0 && board[(y-1)*motiongo.Width+x-1] == player {
		count++
	}
	if x < motiongo.Width-1 && y > 0 && board[(y-1)*motiongo.Width+x+1] == player {
		count++
	}
	if x > 0 && y < motiongo.Height-1 && board[(y+1)*motiongo.Width+x-1] == player {
		count++
	}
	if x < motiongo.Width-1 && y < motiongo.Height-1 && board[(y+1)*motiongo.Width+x+1] == player {
		count++
	}
	return count
}

func handleStartPadPress(pt point, pressed bool, nowNS int64) {
	for player := 0; player < playerCount; player++ {
		if !startPadContains(player, pt) {
			continue
		}
		bit := startBit(startPadOrigin[player], pt)
		if pressed {
			startPadPresses[player] |= bit
			startPadHold[player] = 0
		} else {
			startPadPresses[player] &^= bit
			if startPadPresses[player] == 0 {
				startPadHold[player] = nowNS + startPadHoldNS
			}
		}
	}
	if awaitingPlayers() && allStartPadsOccupied(nowNS) {
		setupStartedNS = nowNS
		setupUntilNS = nowNS + setupDurationNS
		startedNS = setupUntilNS
	}
}

func awaitingPlayers() bool {
	return setupStartedNS == 0
}

func inSetup(nowNS int64) bool {
	return setupUntilNS > 0 && nowNS < setupUntilNS
}

func allStartPadsOccupied(nowNS int64) bool {
	for player := 0; player < playerCount; player++ {
		if !startPadOccupied(player, nowNS) {
			return false
		}
	}
	return true
}

func startPadOccupied(player int, nowNS int64) bool {
	return startPadPresses[player] != 0 || nowNS < startPadHold[player]
}

func startPadColor(pt point, nowNS int64) rgb {
	blinkVisible := awaitingPlayers() || setupBlinkVisible(setupStartedNS, nowNS)
	for player := 0; player < playerCount; player++ {
		if !startPadContains(player, pt) {
			continue
		}
		color := playerStates[player].color
		if startPadOccupied(player, nowNS) {
			return saturatedRGB(color)
		}
		if !blinkVisible {
			return rgb{}
		}
		if awaitingPlayers() {
			return scaleRGB(color, 0.30)
		}
		return color
	}
	return rgb{}
}

func startPadContains(player int, pt point) bool {
	if player < 0 || player >= playerCount {
		return false
	}
	origin := startPadOrigin[player]
	return pt.x >= origin.x && pt.x < origin.x+startPadSize && pt.y >= origin.y && pt.y < origin.y+startPadSize
}

func assignStartPadOrigins() {
	switch playerCount {
	case 2:
		startPadOrigin[0] = point{x: 0, y: (motiongo.Height - startPadSize) / 2}
		startPadOrigin[1] = point{x: motiongo.Width - startPadSize, y: (motiongo.Height - startPadSize) / 2}
	case 3:
		startPadOrigin[0] = point{x: 0, y: 0}
		startPadOrigin[1] = point{x: motiongo.Width - startPadSize, y: 0}
		startPadOrigin[2] = point{x: (motiongo.Width - startPadSize) / 2, y: motiongo.Height - startPadSize}
	default:
		startPadOrigin[0] = point{x: 0, y: 0}
		startPadOrigin[1] = point{x: motiongo.Width - startPadSize, y: motiongo.Height - startPadSize}
		startPadOrigin[2] = point{x: 0, y: motiongo.Height - startPadSize}
		startPadOrigin[3] = point{x: motiongo.Width - startPadSize, y: 0}
		startPadOrigin[4] = point{x: 0, y: (motiongo.Height - startPadSize) / 2}
		startPadOrigin[5] = point{x: motiongo.Width - startPadSize, y: (motiongo.Height - startPadSize) / 2}
		startPadOrigin[6] = point{x: (motiongo.Width - startPadSize) / 2, y: 0}
		startPadOrigin[7] = point{x: (motiongo.Width - startPadSize) / 2, y: motiongo.Height - startPadSize}
	}
}

func remainingTargets() int {
	total := 0
	for player := 0; player < playerCount; player++ {
		total += targetTiles[player] - playerStates[player].score
	}
	return total
}

func playerLabel(index int) string {
	if index >= 0 && index < playerCount && !blankString(playerStates[index].label) {
		return playerStates[index].label
	}
	return "Player " + itoa(index+1)
}

func normalizePlayers(input []motiongo.Player) []motiongo.Player {
	count := clampInt(len(input), minDuelPlayers, maxDuelPlayers)
	out := make([]motiongo.Player, count)
	for i := 0; i < count; i++ {
		fallback := defaultPlayers[i]
		player := fallback
		if i < len(input) {
			player = input[i]
		}
		if blankString(player.Label) {
			player.Label = fallback.Label
		}
		if blankString(player.Color) {
			player.Color = fallback.Color
		}
		player.Index = i
		out[i] = player
	}
	return out
}

func difficultyFillPercent(difficulty string) int {
	switch difficulty {
	case "hard", "dificil":
		return hardFillPct
	case "medium", "medio", "media":
		return mediumFillPct
	default:
		return defaultFillPct
	}
}

func setupBlinkVisible(startedNS int64, nowNS int64) bool {
	if startedNS == 0 || nowNS < startedNS {
		return true
	}
	elapsed := nowNS - startedNS
	if elapsed >= setupDurationNS {
		return false
	}
	halfCycle := setupDurationNS / int64(setupBlinks*2)
	if halfCycle <= 0 {
		return true
	}
	return int(elapsed/halfCycle)%2 == 0
}

func winnerColor(color rgb, pt point, nowNS int64, startedNS int64) rgb {
	elapsed := float64(nowNS-startedNS) / 1000000000
	wave := 0.5 + 0.5*math.Sin(elapsed*math.Pi*3+float64(pt.x)*0.45+float64(pt.y)*0.12)
	burst := 0.55 + 0.45*math.Sin(elapsed*math.Pi*8)
	return addRGB(scaleRGB(color, 0.55+0.45*wave), rgb{int(60 * burst), int(60 * burst), int(60 * burst)})
}

func saturatedRGB(color rgb) rgb {
	return addRGB(color, scaleRGB(color, 0.35))
}

func addRGB(left rgb, right rgb) rgb {
	return rgb{clampByte(left.r + right.r), clampByte(left.g + right.g), clampByte(left.b + right.b)}
}

func scaleRGB(color rgb, scale float64) rgb {
	return rgb{
		clampByte(int(math.Round(float64(color.r) * scale))),
		clampByte(int(math.Round(float64(color.g) * scale))),
		clampByte(int(math.Round(float64(color.b) * scale))),
	}
}

func rgbColor(color rgb) motiongo.Color {
	return motiongo.Color(rgbHex(color))
}

func rgbHex(color rgb) string {
	digits := "0123456789abcdef"
	r := clampByte(color.r)
	g := clampByte(color.g)
	b := clampByte(color.b)
	out := []byte{'#', 0, 0, 0, 0, 0, 0}
	out[1] = digits[(r>>4)&15]
	out[2] = digits[r&15]
	out[3] = digits[(g>>4)&15]
	out[4] = digits[g&15]
	out[5] = digits[(b>>4)&15]
	out[6] = digits[b&15]
	return string(out)
}

func parseColor(value string, fallback rgb) rgb {
	if len(value) != 7 || value[0] != '#' {
		return fallback
	}
	return rgb{
		hexByte(value[1], value[2]),
		hexByte(value[3], value[4]),
		hexByte(value[5], value[6]),
	}
}

func hexByte(high byte, low byte) int {
	return hexNibble(high)*16 + hexNibble(low)
}

func hexNibble(value byte) int {
	if value >= '0' && value <= '9' {
		return int(value - '0')
	}
	if value >= 'a' && value <= 'f' {
		return int(value-'a') + 10
	}
	if value >= 'A' && value <= 'F' {
		return int(value-'A') + 10
	}
	return 0
}

func startBit(origin point, pt point) uint16 {
	index := (pt.y-origin.y)*startPadSize + (pt.x - origin.x)
	if index < 0 || index >= 16 {
		return 0
	}
	return 1 << uint(index)
}

func tileIndex(pt point) int {
	return pt.y*motiongo.Width + pt.x
}

func inBounds(x int, y int) bool {
	return x >= 0 && x < motiongo.Width && y >= 0 && y < motiongo.Height
}

func blankString(value string) bool {
	for i := 0; i < len(value); i++ {
		switch value[i] {
		case ' ', '\n', '\r', '\t':
		default:
			return false
		}
	}
	return true
}

func nextRand() uint32 {
	rng = rng*1664525 + 1013904223
	return rng
}

func nextFloat() float64 {
	return float64(nextRand()&0x00ffffff) / float64(0x01000000)
}

func clampByte(value int) int {
	if value < 0 {
		return 0
	}
	if value > 255 {
		return 255
	}
	return value
}

func clampInt(value int, min int, max int) int {
	if value < min {
		return min
	}
	if value > max {
		return max
	}
	return value
}

func maxInt(a int, b int) int {
	if a > b {
		return a
	}
	return b
}

func itoa(value int) string {
	if value == 0 {
		return "0"
	}
	buf := [12]byte{}
	i := len(buf)
	n := value
	negative := n < 0
	if negative {
		n = -n
	}
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	if negative {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}

func main() {}
`;
