// Code generated by 'make motion-go-seeds' from game-engine/internal/games/authored/nativegames/memorychallengego/game.go. DO NOT EDIT.
export const memoryChallengeMotionGoSource = String.raw`// Code generated from game-engine/internal/games/authored/nativegames/memorychallengego/game.go; edit the engine copy and run 'make motion-go-seeds'.
package main

import (
	"math"

	"github.com/lobis/motion-levels/packages/motiongo"
)

const (
	laneWidth      = 4
	startRows      = 2
	maxPlayers     = 4
	maxPathLen     = 64
	pathFadeNS     = int64(1400000000)
	startGraceNS   = int64(1000000000)
	gameDurationNS = int64(90000000000)
	progressStep   = 5
)

const (
	playerAtStart = iota
	playerRunning
	playerFailed
	playerFinished
)

type point struct {
	x int
	y int
}

type rect struct {
	x int
	y int
	w int
	h int
}

type rgb struct {
	r int
	g int
	b int
}

type playerState struct {
	label        string
	color        rgb
	progress     int
	bestProgress int
	mode         int
	lane         rect
	start        rect
	path         [maxPathLen]point
	pathLen      int
	startPress   uint16
	fadeStarted  int64
	failStarted  int64
	failPoint    point
}

var defaultPlayers = [maxPlayers]motiongo.Player{
	{Index: 0, Label: "Green", Color: "#00ff00"},
	{Index: 1, Label: "Cyan", Color: "#00ffff"},
	{Index: 2, Label: "Pink", Color: "#ff00ff"},
	{Index: 3, Label: "Yellow", Color: "#ffff00"},
}

var players []motiongo.Player
var states [maxPlayers]playerState
var playerCount int
var createdNS int64
var endNS int64
var winner int
var over bool
var rng uint32

//export alloc
func gameAlloc(size uint32) uint32 {
	return motiongo.Alloc(size)
}

//export init
func gameInit(ptr uint32, length uint32) uint64 {
	var req motiongo.InitRequest
	_ = motiongo.Decode(ptr, length, &req)
	players = normalizePlayers(req.Players)
	playerCount = len(players)
	rng = uint32(req.Seed)
	if rng == 0 {
		rng = uint32(req.NowUnixNS)
	}
	createdNS = req.NowUnixNS
	endNS = createdNS + gameDurationNS
	winner = -1
	over = false
	lanes := laneLayout(playerCount)
	for i := 0; i < maxPlayers; i++ {
		states[i] = playerState{}
	}
	for i := 0; i < playerCount; i++ {
		start := startZoneForLane(lanes[i])
		states[i] = playerState{
			label: players[i].Label,
			color: parseColor(players[i].Color, parseColor(defaultPlayers[i].Color, rgb{255, 255, 255})),
			mode:  playerAtStart,
			lane:  lanes[i],
			start: start,
		}
		generateLanePath(i, lanes[i], start)
	}
	return motiongo.Respond([]motiongo.Event{{Cue: "start", Message: "Memoria lista"}})
}

//export press
func gamePress(ptr uint32, length uint32) uint64 {
	var req motiongo.PressRequest
	_ = motiongo.Decode(ptr, length, &req)
	if !inBounds(req.X, req.Y) {
		return motiongo.Respond([]motiongo.Event{})
	}
	expire(req.NowUnixNS)
	if over {
		return motiongo.Respond([]motiongo.Event{})
	}
	pt := point{x: req.X, y: req.Y}
	playerIndex := playerForPoint(pt)
	if playerIndex < 0 {
		return motiongo.Respond([]motiongo.Event{})
	}
	player := &states[playerIndex]
	if req.Pressed && player.mode == playerFailed && returnBandContains(player, pt) {
		returnPlayerToStart(playerIndex)
		return motiongo.Respond([]motiongo.Event{{Cue: "start", Message: player.label + " vuelve"}})
	}
	if contains(player.start, pt) {
		bit := startBit(player.start, pt)
		if req.Pressed {
			player.startPress |= bit
			if player.mode == playerRunning && player.progress == 0 {
				player.fadeStarted = 0
			}
			return motiongo.Respond([]motiongo.Event{})
		}
		player.startPress &^= bit
		if player.mode == playerAtStart && player.startPress == 0 {
			beginPlayerRun(playerIndex, req.NowUnixNS)
		} else if player.mode == playerRunning && player.progress == 0 && player.startPress == 0 {
			schedulePlayerFade(playerIndex, req.NowUnixNS)
		}
		return motiongo.Respond([]motiongo.Event{})
	}
	if !req.Pressed {
		return motiongo.Respond([]motiongo.Event{})
	}
	if player.mode == playerAtStart {
		beginPlayerRun(playerIndex, req.NowUnixNS)
		return motiongo.Respond(handlePathPress(playerIndex, pt, req.NowUnixNS))
	}
	if player.mode == playerRunning {
		return motiongo.Respond(handlePathPress(playerIndex, pt, req.NowUnixNS))
	}
	return motiongo.Respond([]motiongo.Event{})
}

//export tick
func gameTick(ptr uint32, length uint32) uint64 {
	var req motiongo.TimeRequest
	_ = motiongo.Decode(ptr, length, &req)
	expire(req.NowUnixNS)
	return 0
}

//export render
func gameRender(ptr uint32, length uint32) uint64 {
	var req motiongo.TimeRequest
	_ = motiongo.Decode(ptr, length, &req)
	expire(req.NowUnixNS)
	frame := motiongo.NewFrame(motiongo.Black)
	t := timePhase(req.NowUnixNS)
	for y := 0; y < motiongo.Height; y++ {
		for x := 0; x < motiongo.Width; x++ {
			frame.Set(x, y, rgbColor(colorAt(point{x: x, y: y}, req.NowUnixNS, t)))
		}
	}
	return motiongo.Respond(frame)
}

//export snapshot
func gameSnapshot(ptr uint32, length uint32) uint64 {
	var req motiongo.TimeRequest
	_ = motiongo.Decode(ptr, length, &req)
	expire(req.NowUnixNS)
	phase := "ready"
	running := false
	failed := false
	for i := 0; i < playerCount; i++ {
		if states[i].mode == playerRunning {
			running = true
		}
		if states[i].mode == playerFailed {
			failed = true
		}
	}
	if running {
		phase = "running"
	}
	if failed {
		phase = "failed"
	}
	if over {
		phase = "finished"
	}
	best := 0
	activeTargets := 0
	snapPlayers := make([]motiongo.PlayerSnapshot, 0, playerCount)
	for i := 0; i < playerCount; i++ {
		player := states[i]
		if player.bestProgress > best {
			best = player.bestProgress
		}
		activeTargets += maxInt(0, player.pathLen-player.bestProgress)
		snapPlayers = append(snapPlayers, motiongo.PlayerSnapshot{
			Index: i,
			Label: player.label,
			Color: rgbHex(player.color),
			Score: player.bestProgress,
			Lives: -1,
		})
	}
	elapsed := int64(0)
	if req.NowUnixNS > createdNS {
		elapsed = (req.NowUnixNS - createdNS) / 1000000
	}
	remaining := int64(0)
	if req.NowUnixNS < endNS && !over {
		remaining = (endNS - req.NowUnixNS) / 1000000
	}
	return motiongo.Respond(motiongo.Snapshot{
		Phase:           phase,
		Score:           best,
		StartedUnix:     createdNS / 1000000000,
		EndsUnix:        endNS / 1000000000,
		ElapsedMillis:   elapsed,
		RemainingMillis: remaining,
		ActiveTargets:   activeTargets,
		Lives:           -1,
		Success:         winner >= 0,
		Players:         snapPlayers,
	})
}

func beginPlayerRun(playerIndex int, nowNS int64) {
	if playerIndex < 0 || playerIndex >= playerCount {
		return
	}
	player := &states[playerIndex]
	if player.mode == playerFinished {
		return
	}
	player.mode = playerRunning
	schedulePlayerFade(playerIndex, nowNS)
}

func schedulePlayerFade(playerIndex int, nowNS int64) {
	player := &states[playerIndex]
	if player.startPress != 0 {
		player.fadeStarted = 0
		return
	}
	player.fadeStarted = nowNS + startGraceNS
}

func returnPlayerToStart(playerIndex int) {
	player := &states[playerIndex]
	player.mode = playerAtStart
	player.startPress = 0
	player.fadeStarted = 0
	player.failStarted = 0
}

func handlePathPress(playerIndex int, pt point, nowNS int64) []motiongo.Event {
	player := &states[playerIndex]
	if player.mode != playerRunning {
		return []motiongo.Event{}
	}
	if player.progress < player.pathLen && samePoint(pt, player.path[player.progress]) {
		if player.progress == 0 {
			player.fadeStarted = nowNS
		}
		player.progress++
		if player.progress > player.bestProgress {
			player.bestProgress = player.progress
		}
		if player.progress >= player.pathLen {
			finishPlayer(playerIndex)
			return []motiongo.Event{{Cue: "win", Message: "Memoria gana " + player.label}}
		}
		if shouldEmitProgress(player.progress, player.pathLen) {
			return []motiongo.Event{{Cue: "coin", Message: player.label + " " + itoa(player.progress)}}
		}
		return []motiongo.Event{}
	}
	index := pathIndex(player, pt)
	if index >= 0 && index < player.progress {
		return []motiongo.Event{}
	}
	failPlayer(playerIndex, pt, nowNS)
	return []motiongo.Event{{Cue: "damage", Message: player.label + " falló"}}
}

func shouldEmitProgress(progress int, pathLength int) bool {
	return progress == 1 || progress%progressStep == 0 || progress >= pathLength
}

func failPlayer(playerIndex int, pt point, nowNS int64) {
	player := &states[playerIndex]
	if player.mode != playerRunning && player.mode != playerAtStart {
		return
	}
	player.progress = 0
	player.failPoint = pt
	player.failStarted = nowNS
	player.fadeStarted = 0
	player.startPress = 0
	player.mode = playerFailed
}

func finishPlayer(playerIndex int) {
	player := &states[playerIndex]
	player.mode = playerFinished
	player.bestProgress = player.pathLen
	winner = playerIndex
	over = true
}

func expire(nowNS int64) bool {
	if over || endNS == 0 || nowNS < endNS {
		return false
	}
	over = true
	return true
}

func colorAt(pt point, nowNS int64, t float64) rgb {
	playerIndex := playerForPoint(pt)
	if playerIndex < 0 {
		return lavaColor(pt.x, pt.y, t, 0.32)
	}
	player := states[playerIndex]
	color := player.color
	if over {
		return gameOverColor(playerIndex, pt, t)
	}
	if contains(player.start, pt) {
		return startColor(playerIndex, pt, t)
	}
	if player.mode == playerFailed && samePoint(pt, player.failPoint) {
		pulse := (math.Sin(t*12) + 1) / 2
		return rgb{255, clampByte(130 + int(100*pulse)), clampByte(60 + int(130*pulse))}
	}
	if player.mode == playerFailed && manhattan(pt, player.failPoint) <= 2 && int(t*10)%6 < 3 {
		return addRGB(lavaColor(pt.x, pt.y, t, 1), rgb{90, 22, 0})
	}
	index := pathIndex(&player, pt)
	if index >= 0 {
		return pathColor(player, color, pt, index, nowNS, t)
	}
	return lavaColor(pt.x, pt.y, t, 1)
}

func startColor(playerIndex int, pt point, t float64) rgb {
	player := states[playerIndex]
	color := player.color
	pulse := (math.Sin(t*5+float64(pt.x)*0.4) + 1) / 2
	factor := 0.30 + 0.34*pulse
	if player.mode == playerAtStart || player.startPress != 0 {
		factor = 0.58 + 0.36*pulse
	}
	if player.mode == playerFailed {
		factor = 0.44 + 0.48*pulse
	}
	if player.mode == playerFinished {
		factor = 0.70 + 0.28*pulse
	}
	if player.startPress != 0 {
		return addRGB(scaleRGB(color, factor), scaleRGB(rgb{255, 255, 255}, 0.28))
	}
	return scaleRGB(color, factor)
}

func pathColor(player playerState, color rgb, pt point, index int, nowNS int64, t float64) rgb {
	pulse := (math.Sin(t*4+float64(index)*0.14) + 1) / 2
	switch player.mode {
	case playerAtStart:
		return pathLitColor(color, pulse)
	case playerFailed:
		if int(t*10)%6 < 3 {
			return pathLitColor(color, pulse)
		}
		return scaleRGB(color, 0.12+0.18*pulse)
	case playerRunning:
		if index < player.progress {
			return pathLitColor(color, pulse)
		}
		if player.fadeStarted == 0 || nowNS < player.fadeStarted {
			return pathLitColor(color, pulse)
		}
		ratio := 1 - clamp01(float64(nowNS-player.fadeStarted)/float64(pathFadeNS))
		if ratio > 0 {
			return blendRGB(lavaColor(pt.x, pt.y, t, 1), pathLitColor(color, pulse), ratio)
		}
		return lavaColor(pt.x, pt.y, t, 1)
	case playerFinished:
		return pathLitColor(color, pulse)
	default:
		return lavaColor(pt.x, pt.y, t, 1)
	}
}

func pathLitColor(color rgb, pulse float64) rgb {
	return scaleRGB(color, 0.84+0.16*pulse)
}

func gameOverColor(playerIndex int, pt point, t float64) rgb {
	if winner < 0 {
		if int(t*10)%8 < 4 {
			return rgb{255, 28, 0}
		}
		return lavaColor(pt.x, pt.y, t, 0.72)
	}
	if playerIndex != winner {
		return lavaColor(pt.x, pt.y, t, 0.50)
	}
	color := states[playerIndex].color
	player := states[playerIndex]
	pulse := (math.Sin(t*8) + 1) / 2
	if contains(player.start, pt) {
		return addRGB(scaleRGB(color, 0.74+0.24*pulse), scaleRGB(rgb{255, 255, 255}, 0.20+0.25*pulse))
	}
	index := pathIndex(&player, pt)
	if index >= 0 {
		tick := int(t * 20)
		if traceTile(player, index, tick) {
			return rgb{255 - color.r, 255 - color.g, 255 - color.b}
		}
		return pathLitColor(color, pulse)
	}
	return blendRGB(lavaColor(pt.x, pt.y, t, 0.82), color, 0.30+0.28*pulse)
}

func traceTile(player playerState, index int, tick int) bool {
	if player.pathLen == 0 || index < 0 {
		return false
	}
	traceIndex := player.pathLen - 1 - (tick % player.pathLen)
	return index == traceIndex
}

func lavaColor(x int, y int, t float64, intensity float64) rgb {
	flicker := (math.Sin(float64(x)*0.83+float64(y)*0.37+t*2.2) + 1) / 2
	flow := (math.Sin(float64(y)*0.55+t*1.4) + 1) / 2
	ember := (math.Sin(float64(x+y)*0.41+t*3.7) + 1) / 2
	r := clampByte(int((18 + 54*flicker + 16*ember) * intensity))
	g := clampByte(int((2 + 16*flow + 6*ember) * intensity))
	b := clampByte(int((1 + 4*(1-flicker)) * intensity))
	return rgb{r, g, b}
}

func playerForPoint(pt point) int {
	for i := 0; i < playerCount; i++ {
		if contains(states[i].lane, pt) {
			return i
		}
	}
	return -1
}

func laneLayout(count int) [maxPlayers]rect {
	count = clampInt(count, 1, maxPlayers)
	var lanes [maxPlayers]rect
	switch count {
	case 1:
		lanes[0] = rect{0, 0, motiongo.Width, motiongo.Height}
	case 2:
		lanes[0] = rect{0, 0, motiongo.Width / 2, motiongo.Height}
		lanes[1] = rect{motiongo.Width / 2, 0, motiongo.Width / 2, motiongo.Height}
	case 3:
		lanes[0] = rect{0, 0, laneWidth, motiongo.Height}
		lanes[1] = rect{6, 0, laneWidth, motiongo.Height}
		lanes[2] = rect{12, 0, laneWidth, motiongo.Height}
	default:
		lanes[0] = rect{0, 0, laneWidth, motiongo.Height}
		lanes[1] = rect{4, 0, laneWidth, motiongo.Height}
		lanes[2] = rect{8, 0, laneWidth, motiongo.Height}
		lanes[3] = rect{12, 0, laneWidth, motiongo.Height}
	}
	return lanes
}

func startZoneForLane(lane rect) rect {
	width := laneWidth
	if lane.w < width {
		width = lane.w
	}
	return rect{x: lane.x + (lane.w-width)/2, y: 0, w: width, h: startRows}
}

func generateLanePath(playerIndex int, lane rect, start rect) {
	for attempt := 0; attempt < 1000; attempt++ {
		candidateLanePath(playerIndex, lane, start)
		if pathOrderUnambiguous(states[playerIndex]) {
			return
		}
	}
	straightLanePath(playerIndex, lane, start)
}

func candidateLanePath(playerIndex int, lane rect, start rect) {
	player := &states[playerIndex]
	player.pathLen = 0
	x := start.x + int(nextRand()%uint32(start.w))
	y := startRows
	appendPath(player, point{x, y})
	segmentRows := 3 + int(nextRand()%4)
	for y < motiongo.Height-1 {
		if segmentRows <= 0 {
			var candidates [2]int
			count := 0
			if x > lane.x {
				candidates[count] = x - 1
				count++
			}
			if x < lane.x+lane.w-1 {
				candidates[count] = x + 1
				count++
			}
			if count > 0 {
				x = candidates[int(nextRand()%uint32(count))]
				appendPath(player, point{x, y})
			}
			segmentRows = 3 + int(nextRand()%5)
		}
		y++
		appendPath(player, point{x, y})
		segmentRows--
	}
}

func straightLanePath(playerIndex int, lane rect, start rect) {
	player := &states[playerIndex]
	player.pathLen = 0
	x := start.x + start.w/2
	for y := startRows; y < motiongo.Height; y++ {
		appendPath(player, point{x, y})
	}
}

func appendPath(player *playerState, pt point) {
	if player.pathLen >= maxPathLen {
		return
	}
	player.path[player.pathLen] = pt
	player.pathLen++
}

func pathOrderUnambiguous(player playerState) bool {
	if player.pathLen < 2 {
		return false
	}
	for i := 0; i < player.pathLen; i++ {
		pt := player.path[i]
		for j := 0; j < player.pathLen; j++ {
			other := player.path[j]
			if i != j && samePoint(pt, other) {
				return false
			}
			if absInt(i-j) <= 1 {
				continue
			}
			if manhattan(pt, other) == 1 {
				return false
			}
		}
		if i > 0 && manhattan(pt, player.path[i-1]) != 1 {
			return false
		}
	}
	return true
}

func pathIndex(player *playerState, pt point) int {
	for i := 0; i < player.pathLen; i++ {
		if samePoint(player.path[i], pt) {
			return i
		}
	}
	return -1
}

func normalizePlayers(input []motiongo.Player) []motiongo.Player {
	count := clampInt(len(input), 1, maxPlayers)
	out := make([]motiongo.Player, count)
	for i := 0; i < count; i++ {
		fallback := defaultPlayers[i]
		player := fallback
		if i < len(input) {
			player = input[i]
		}
		if blankString(player.Label) {
			player.Label = fallback.Label
		}
		if blankString(player.Color) {
			player.Color = fallback.Color
		}
		player.Index = i
		out[i] = player
	}
	return out
}

func returnBandContains(player *playerState, pt point) bool {
	return contains(player.lane, pt) && pt.y >= 0 && pt.y < startRows
}

func startBit(start rect, pt point) uint16 {
	index := (pt.y-start.y)*start.w + (pt.x - start.x)
	if index < 0 || index >= 16 {
		return 0
	}
	return 1 << uint(index)
}

func contains(r rect, pt point) bool {
	return pt.x >= r.x && pt.x < r.x+r.w && pt.y >= r.y && pt.y < r.y+r.h
}

func samePoint(a point, b point) bool {
	return a.x == b.x && a.y == b.y
}

func timePhase(nowNS int64) float64 {
	if nowNS < createdNS {
		return 0
	}
	return float64(nowNS-createdNS) / 1000000000 * 2.2
}

func manhattan(a point, b point) int {
	return absInt(a.x-b.x) + absInt(a.y-b.y)
}

func blendRGB(left rgb, right rgb, ratio float64) rgb {
	ratio = clamp01(ratio)
	return rgb{
		clampByte(int(float64(left.r)*(1-ratio) + float64(right.r)*ratio)),
		clampByte(int(float64(left.g)*(1-ratio) + float64(right.g)*ratio)),
		clampByte(int(float64(left.b)*(1-ratio) + float64(right.b)*ratio)),
	}
}

func addRGB(left rgb, right rgb) rgb {
	return rgb{clampByte(left.r + right.r), clampByte(left.g + right.g), clampByte(left.b + right.b)}
}

func scaleRGB(color rgb, scale float64) rgb {
	return rgb{
		clampByte(int(math.Round(float64(color.r) * scale))),
		clampByte(int(math.Round(float64(color.g) * scale))),
		clampByte(int(math.Round(float64(color.b) * scale))),
	}
}

func rgbColor(color rgb) motiongo.Color {
	return motiongo.Color(rgbHex(color))
}

func rgbHex(color rgb) string {
	digits := "0123456789abcdef"
	r := clampByte(color.r)
	g := clampByte(color.g)
	b := clampByte(color.b)
	out := []byte{'#', 0, 0, 0, 0, 0, 0}
	out[1] = digits[(r>>4)&15]
	out[2] = digits[r&15]
	out[3] = digits[(g>>4)&15]
	out[4] = digits[g&15]
	out[5] = digits[(b>>4)&15]
	out[6] = digits[b&15]
	return string(out)
}

func parseColor(value string, fallback rgb) rgb {
	if len(value) != 7 || value[0] != '#' {
		return fallback
	}
	return rgb{
		hexByte(value[1], value[2]),
		hexByte(value[3], value[4]),
		hexByte(value[5], value[6]),
	}
}

func hexByte(high byte, low byte) int {
	return hexNibble(high)*16 + hexNibble(low)
}

func hexNibble(value byte) int {
	if value >= '0' && value <= '9' {
		return int(value - '0')
	}
	if value >= 'a' && value <= 'f' {
		return int(value-'a') + 10
	}
	if value >= 'A' && value <= 'F' {
		return int(value-'A') + 10
	}
	return 0
}

func clampByte(value int) int {
	if value < 0 {
		return 0
	}
	if value > 255 {
		return 255
	}
	return value
}

func clamp01(value float64) float64 {
	if value < 0 {
		return 0
	}
	if value > 1 {
		return 1
	}
	return value
}

func clampInt(value int, min int, max int) int {
	if value < min {
		return min
	}
	if value > max {
		return max
	}
	return value
}

func maxInt(a int, b int) int {
	if a > b {
		return a
	}
	return b
}

func absInt(value int) int {
	if value < 0 {
		return -value
	}
	return value
}

func inBounds(x int, y int) bool {
	return x >= 0 && x < motiongo.Width && y >= 0 && y < motiongo.Height
}

func blankString(value string) bool {
	for i := 0; i < len(value); i++ {
		switch value[i] {
		case ' ', '\n', '\r', '\t':
		default:
			return false
		}
	}
	return true
}

func nextRand() uint32 {
	rng = rng*1664525 + 1013904223
	return rng
}

func itoa(value int) string {
	if value == 0 {
		return "0"
	}
	buf := [12]byte{}
	i := len(buf)
	n := value
	negative := n < 0
	if negative {
		n = -n
	}
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	if negative {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}

func main() {}
`;
