// Code generated by 'make motion-go-seeds' from game-engine/internal/games/authored/nativegames/pingpongv2/game.go. DO NOT EDIT.
export const pingPongV2MotionGoSource = String.raw`// Code generated from game-engine/internal/games/authored/nativegames/pingpongv2/game.go; edit the engine copy and run 'make motion-go-seeds'.
package main

import "github.com/lobis/motion-levels/packages/motiongo"

const (
	redColor              = "#ff1c28"
	blueColor             = "#145cff"
	defaultWinningScore   = 5
	readyAnimationNS      = int64(2000000000)
	startGraceNS          = int64(1000000000)
	postPointPauseNS      = int64(900000000)
	winAnimationNS        = int64(3000000000)
	paddleYRed            = 2
	paddleYBlue           = 29
	paddleWidth           = 5
	serveX                = motiongo.Width / 2
	serveY                = motiongo.Height / 2
	defaultIntervalEasy   = int64(180000000)
	defaultIntervalMedium = int64(140000000)
	defaultIntervalHard   = int64(105000000)
	minIntervalEasy       = int64(72000000)
	minIntervalMedium     = int64(56000000)
	minIntervalHard       = int64(42000000)
	speedStepNS           = int64(4500000)
)

type rgb struct {
	r int
	g int
	b int
}

var redRGB = rgb{255, 28, 40}
var blueRGB = rgb{20, 92, 255}
var whiteRGB = rgb{255, 255, 255}

var players []motiongo.Player
var winningScore int
var startedNS int64
var readyNS int64
var lastStepNS int64
var pauseUntilNS int64
var finishNS int64
var rng uint32
var initialIntervalNS int64
var minimumIntervalNS int64
var currentIntervalNS int64
var hitCount int
var redPaddleX int
var bluePaddleX int
var ballX int
var ballY int
var ballDX int
var ballDY int
var teamScore [2]int
var tileHeld [motiongo.Width * motiongo.Height]bool
var halfHeld [2]int
var halfGraceUntil [2]int64
var rounds []motiongo.RoundSnapshot
var lastRoundHits int
var lastRoundWinner string
var phase string
var success bool
var scorer int
var winner int
var lastMessage string

//export alloc
func gameAlloc(size uint32) uint32 {
	return motiongo.Alloc(size)
}

//export init
func gameInit(ptr uint32, length uint32) uint64 {
	var req motiongo.InitRequest
	_ = motiongo.Decode(ptr, length, &req)
	players = req.Players
	if len(players) == 0 {
		players = []motiongo.Player{
			{Index: 0, Label: "Rojo", Color: redColor},
			{Index: 1, Label: "Azul", Color: blueColor},
		}
	}
	if len(players) > motiongo.MaxStartPadPlayers {
		players = players[:motiongo.MaxStartPadPlayers]
	}
	rng = uint32(req.Seed)
	if rng == 0 {
		rng = 202
	}
	winningScore = clamp(req.Config.Int("points_to_win", defaultWinningScore), 1, 21)
	initialIntervalNS, minimumIntervalNS = speedForDifficulty(req.Difficulty)
	startedNS = req.NowUnixNS
	resetGame(req.NowUnixNS)
	return motiongo.Respond([]motiongo.Event{{Cue: "ready", Message: "Ping Pong V2 espera rojo y azul."}})
}

//export press
func gamePress(ptr uint32, length uint32) uint64 {
	var req motiongo.PressRequest
	_ = motiongo.Decode(ptr, length, &req)
	updateOccupancy(req.X, req.Y, req.Pressed, req.NowUnixNS)
	if req.Pressed {
		movePaddle(req.X, req.Y)
	}
	events := updatePhase(req.NowUnixNS)
	return motiongo.Respond(events)
}

//export tick
func gameTick(ptr uint32, length uint32) uint64 {
	var req motiongo.TimeRequest
	_ = motiongo.Decode(ptr, length, &req)
	events := updatePhase(req.NowUnixNS)
	if phase != "running" {
		if len(events) == 0 {
			return 0
		}
		return motiongo.Respond(events)
	}
	if req.NowUnixNS < pauseUntilNS {
		if len(events) == 0 {
			return 0
		}
		return motiongo.Respond(events)
	}

	steps := 0
	for steps < 8 {
		if req.NowUnixNS-lastStepNS < currentIntervalNS {
			break
		}
		lastStepNS += currentIntervalNS
		event := moveBall(lastStepNS)
		if event.Message != "" {
			events = append(events, event)
		}
		steps++
		if phase != "running" || lastStepNS < pauseUntilNS {
			break
		}
	}
	if len(events) == 0 {
		return 0
	}
	return motiongo.Respond(events)
}

//export render
func gameRender(ptr uint32, length uint32) uint64 {
	var req motiongo.TimeRequest
	_ = motiongo.Decode(ptr, length, &req)
	frame := motiongo.NewFrame(motiongo.Black)

	if phase == "waiting" {
		drawWaiting(&frame, req.NowUnixNS)
		return motiongo.Respond(frame)
	}
	if phase == "starting" {
		drawReady(&frame, req.NowUnixNS)
		return motiongo.Respond(frame)
	}
	if phase == "finished" {
		drawWin(&frame, req.NowUnixNS)
		return motiongo.Respond(frame)
	}

	drawScore(&frame)
	drawPaddles(&frame)
	if req.NowUnixNS < pauseUntilNS {
		drawScoreFlash(&frame, req.NowUnixNS)
	} else {
		frame.FillRect(ballX, ballY, 1, 1, motiongo.White)
	}
	return motiongo.Respond(frame)
}

//export snapshot
func gameSnapshot(ptr uint32, length uint32) uint64 {
	var req motiongo.TimeRequest
	_ = motiongo.Decode(ptr, length, &req)
	_ = updatePhase(req.NowUnixNS)

	countdown := int64(0)
	if phase == "starting" && req.NowUnixNS < readyNS {
		countdown = (readyNS - req.NowUnixNS) / 1000000
	}
	remaining := int64(0)
	if phase == "finished" && req.NowUnixNS < finishNS+winAnimationNS {
		remaining = (finishNS + winAnimationNS - req.NowUnixNS) / 1000000
	}

	return motiongo.Respond(motiongo.Snapshot{
		Phase:           phase,
		Score:           teamScore[0] + teamScore[1],
		StartedUnix:     startedNS / 1000000000,
		EndsUnix:        0,
		ElapsedMillis:   (req.NowUnixNS - startedNS) / 1000000,
		RemainingMillis: remaining,
		CountdownMillis: countdown,
		ActiveTargets:   activeHalves(req.NowUnixNS),
		Success:         success,
		MatchTarget:     winningScore,
		RoundHits:       hitCount,
		LastRoundHits:   lastRoundHits,
		LastRoundWinner: lastRoundWinner,
		Rounds:          rounds,
		Players: []motiongo.PlayerSnapshot{
			{Index: 0, Label: labelForTeam(0), Color: redColor, Score: teamScore[0], Lives: winningScore - teamScore[0]},
			{Index: 1, Label: labelForTeam(1), Color: blueColor, Score: teamScore[1], Lives: winningScore - teamScore[1]},
		},
	})
}

func resetGame(nowNS int64) {
	for i := 0; i < len(tileHeld); i++ {
		tileHeld[i] = false
	}
	halfHeld[0] = 0
	halfHeld[1] = 0
	halfGraceUntil[0] = 0
	halfGraceUntil[1] = 0
	teamScore[0] = 0
	teamScore[1] = 0
	rounds = nil
	lastRoundHits = 0
	lastRoundWinner = ""
	redPaddleX = (motiongo.Width - paddleWidth) / 2
	bluePaddleX = redPaddleX
	phase = "waiting"
	success = false
	scorer = -1
	winner = -1
	startedNS = nowNS
	readyNS = 0
	finishNS = 0
	resetBall()
	lastMessage = "Esperando a rojo arriba y azul abajo."
}

func updatePhase(nowNS int64) []motiongo.Event {
	events := []motiongo.Event{}
	if phase == "finished" {
		if nowNS-finishNS >= winAnimationNS {
			resetGame(nowNS)
			events = append(events, motiongo.Event{Cue: "ready", Message: "Nueva partida."})
		}
		return events
	}
	if phase == "waiting" && halvesReady(nowNS) {
		phase = "starting"
		readyNS = nowNS + readyAnimationNS
		lastMessage = "Rojo y azul listos."
		return append(events, motiongo.Event{Cue: "start", Message: "Rojo y azul listos."})
	}
	if phase == "starting" {
		if nowNS >= readyNS {
			phase = "running"
			startedNS = nowNS
			lastStepNS = nowNS
			serve()
			return append(events, motiongo.Event{Cue: "start", Message: "La pelota esta en juego."})
		}
	}
	return events
}

func updateOccupancy(x int, y int, pressed bool, nowNS int64) {
	if x < 0 || x >= motiongo.Width || y < 0 || y >= motiongo.Height {
		return
	}
	index := y*motiongo.Width + x
	if tileHeld[index] == pressed {
		return
	}
	tileHeld[index] = pressed
	half := halfForY(y)
	if pressed {
		halfHeld[half]++
		halfGraceUntil[half] = nowNS + startGraceNS
	} else if halfHeld[half] > 0 {
		halfHeld[half]--
		if halfHeld[half] == 0 {
			halfGraceUntil[half] = nowNS + startGraceNS
		}
	}
}

func movePaddle(x int, y int) {
	center := clamp(x, paddleWidth/2, motiongo.Width-1-paddleWidth/2)
	left := center - paddleWidth/2
	if y < motiongo.Height/2 {
		redPaddleX = left
	} else {
		bluePaddleX = left
	}
}

func moveBall(nowNS int64) motiongo.Event {
	nextX := ballX + ballDX
	nextY := ballY + ballDY
	if nextX < 0 {
		nextX = 0
		ballDX = 1
	}
	if nextX >= motiongo.Width {
		nextX = motiongo.Width - 1
		ballDX = -1
	}
	if ballDY < 0 && nextY == paddleYRed && nextX >= redPaddleX && nextX < redPaddleX+paddleWidth {
		reflectFromPaddle(nextX, redPaddleX)
		ballDY = 1
		ballX = nextX
		ballY = paddleYRed + 1
		accelerate()
		return motiongo.Event{Cue: "coin", Message: "Rojo devuelve."}
	}
	if ballDY > 0 && nextY == paddleYBlue && nextX >= bluePaddleX && nextX < bluePaddleX+paddleWidth {
		reflectFromPaddle(nextX, bluePaddleX)
		ballDY = -1
		ballX = nextX
		ballY = paddleYBlue - 1
		accelerate()
		return motiongo.Event{Cue: "coin", Message: "Azul devuelve."}
	}
	if nextY < 0 {
		scorePoint(1, nowNS)
		return motiongo.Event{Cue: "score", Message: "Punto para azul."}
	}
	if nextY >= motiongo.Height {
		scorePoint(0, nowNS)
		return motiongo.Event{Cue: "score", Message: "Punto para rojo."}
	}
	ballX = nextX
	ballY = nextY
	return motiongo.Event{}
}

func scorePoint(team int, nowNS int64) {
	teamScore[team]++
	scorer = team
	recordRound(team)
	if teamScore[team] >= winningScore {
		phase = "finished"
		success = team == 1
		winner = team
		finishNS = nowNS
		if team == 0 {
			lastMessage = "Gana rojo."
		} else {
			lastMessage = "Gana azul."
		}
		return
	}
	resetBall()
	pauseUntilNS = nowNS + postPointPauseNS
	lastStepNS = pauseUntilNS
	lastMessage = "Nuevo saque."
}

func recordRound(team int) {
	lastRoundHits = hitCount
	lastRoundWinner = labelForTeam(team)
	rounds = append(rounds, motiongo.RoundSnapshot{
		Index:       len(rounds) + 1,
		WinnerIndex: team,
		WinnerLabel: lastRoundWinner,
		Hits:        lastRoundHits,
	})
}

func resetBall() {
	ballX = serveX
	ballY = serveY
	currentIntervalNS = initialIntervalNS
	hitCount = 0
	pauseUntilNS = 0
	serve()
}

func serve() {
	ballX = serveX
	ballY = serveY
	rng = rng*1664525 + 1013904223
	if rng%2 == 0 {
		ballDY = -1
	} else {
		ballDY = 1
	}
	rng = rng*1664525 + 1013904223
	if rng%2 == 0 {
		ballDX = -1
	} else {
		ballDX = 1
	}
}

func reflectFromPaddle(x int, paddleX int) {
	center := paddleX + paddleWidth/2
	if x < center {
		ballDX = -1
	} else if x > center {
		ballDX = 1
	} else {
		rng = rng*1664525 + 1013904223
		if rng%2 == 0 {
			ballDX = -1
		} else {
			ballDX = 1
		}
	}
}

func accelerate() {
	hitCount++
	currentIntervalNS = initialIntervalNS - int64(hitCount)*speedStepNS
	if currentIntervalNS < minimumIntervalNS {
		currentIntervalNS = minimumIntervalNS
	}
}

func drawWaiting(frame *motiongo.Frame, nowNS int64) {
	pulse := int((nowNS / 180000000) % 4)
	redReady := halfReady(0, nowNS)
	blueReady := halfReady(1, nowNS)
	drawWaitingHalf(frame, 0, redReady, nowNS)
	drawWaitingHalf(frame, 1, blueReady, nowNS)
	if redReady {
		drawSoftBar(frame, 3, 5, 10, redRGB, nowNS)
	} else {
		drawOutline(frame, 2+pulse, 4+pulse, motiongo.Width-4-pulse*2, 6, motiongo.Color(redColor))
	}
	if blueReady {
		drawSoftBar(frame, 3, 24, 10, blueRGB, nowNS)
	} else {
		drawOutline(frame, 2+pulse, 22-pulse, motiongo.Width-4-pulse*2, 6, motiongo.Color(blueColor))
	}
}

func drawReady(frame *motiongo.Frame, nowNS int64) {
	elapsed := nowNS - (readyNS - readyAnimationNS)
	if elapsed < 0 {
		elapsed = 0
	}
	radius := int(elapsed * int64(motiongo.Width/2) / readyAnimationNS)
	if radius < 1 {
		radius = 1
	}
	if radius > motiongo.Width/2 {
		radius = motiongo.Width / 2
	}
	wave := int(elapsed / 90000000)
	for y := 0; y < motiongo.Height; y++ {
		for x := 0; x < motiongo.Width; x++ {
			dx := abs(x - serveX)
			dy := abs(y - serveY)
			dist := dx + dy
			base := redRGB
			if y >= motiongo.Height/2 {
				base = blueRGB
			}
			if dist <= radius+1 {
				level := 35 + (radius-dist+1)*18
				frame.Set(x, y, rgbColor(addRGB(scaleRGB(base, level), scaleRGB(whiteRGB, maxInt(0, 22-dist*3)))))
			} else if (dist+wave)%7 == 0 {
				frame.Set(x, y, rgbColor(scaleRGB(base, 24)))
			}
		}
	}
	frame.Set(serveX, serveY, rgbColor(whiteRGB))
}

func drawScoreFlash(frame *motiongo.Frame, nowNS int64) {
	base := redRGB
	if scorer == 1 {
		base = blueRGB
	}
	wave := int(((pauseUntilNS - nowNS) / 90000000) % 5)
	for y := 0; y < motiongo.Height; y++ {
		for x := 0; x < motiongo.Width; x++ {
			dist := abs(y - serveY)
			if (x+y+wave)%5 == 0 {
				frame.Set(x, y, rgbColor(addRGB(scaleRGB(base, 38+dist*3), scaleRGB(whiteRGB, maxInt(0, 18-dist)))))
			} else if dist < 4 {
				frame.Set(x, y, rgbColor(scaleRGB(base, 14)))
			}
		}
	}
	drawPaddles(frame)
}

func drawWin(frame *motiongo.Frame, nowNS int64) {
	base := redRGB
	if winner == 1 {
		base = blueRGB
	}
	phaseStep := int((nowNS / 90000000) % 16)
	for y := 0; y < motiongo.Height; y++ {
		for x := 0; x < motiongo.Width; x++ {
			dist := abs(x-serveX) + abs(y-serveY)
			band := (dist + phaseStep) % 12
			if band < 5 {
				level := 28 + (5-band)*16
				frame.Set(x, y, rgbColor(addRGB(scaleRGB(base, level), scaleRGB(whiteRGB, maxInt(0, 26-band*4)))))
			} else if (x+y+phaseStep)%9 == 0 {
				frame.Set(x, y, rgbColor(scaleRGB(base, 34)))
			}
		}
	}
	frame.FillRect(serveX-1, serveY-1, 3, 3, rgbColor(scaleRGB(whiteRGB, 85)))
	frame.Set(serveX, serveY, motiongo.White)
}

func drawScore(frame *motiongo.Frame) {
	for i := 0; i < teamScore[0] && i < motiongo.Width; i++ {
		frame.Set(i, 0, motiongo.Color(redColor))
	}
	for i := 0; i < teamScore[1] && i < motiongo.Width; i++ {
		frame.Set(i, motiongo.Height-1, motiongo.Color(blueColor))
	}
}

func drawPaddles(frame *motiongo.Frame) {
	drawPaddle(frame, redPaddleX, paddleYRed, redRGB)
	drawPaddle(frame, bluePaddleX, paddleYBlue, blueRGB)
}

func drawWaitingHalf(frame *motiongo.Frame, half int, ready bool, nowNS int64) {
	startY := 0
	base := redRGB
	if half == 1 {
		startY = motiongo.Height / 2
		base = blueRGB
	}
	pulse := int((nowNS / 120000000) % 10)
	for y := startY; y < startY+motiongo.Height/2; y++ {
		for x := 0; x < motiongo.Width; x++ {
			level := 0
			if ready {
				level = 18 + ((x+y+pulse)%6)*6
			} else if (x+y+pulse)%7 == 0 {
				level = 22
			}
			if level > 0 {
				frame.Set(x, y, rgbColor(scaleRGB(base, level)))
			}
		}
	}
}

func drawSoftBar(frame *motiongo.Frame, x int, y int, width int, base rgb, nowNS int64) {
	pulse := int((nowNS / 100000000) % 6)
	for xx := 0; xx < width; xx++ {
		level := 58 + xx*4
		if xx == pulse || xx == width-1-pulse {
			level = 112
		}
		frame.Set(x+xx, y, rgbColor(scaleRGB(base, level)))
		frame.Set(x+xx, y+1, rgbColor(addRGB(scaleRGB(base, level-8), scaleRGB(whiteRGB, 10))))
		frame.Set(x+xx, y+2, rgbColor(scaleRGB(base, maxInt(18, level-28))))
	}
}

func drawPaddle(frame *motiongo.Frame, x int, y int, base rgb) {
	for offset := 0; offset < paddleWidth; offset++ {
		level := 74
		if offset == paddleWidth/2 {
			level = 118
		}
		frame.Set(x+offset, y, rgbColor(addRGB(scaleRGB(base, level), scaleRGB(whiteRGB, 18))))
	}
}

func drawOutline(frame *motiongo.Frame, x int, y int, width int, height int, color motiongo.Color) {
	if width < 2 {
		width = 2
	}
	if height < 2 {
		height = 2
	}
	frame.FillRect(x, y, width, 1, color)
	frame.FillRect(x, y+height-1, width, 1, color)
	frame.FillRect(x, y, 1, height, color)
	frame.FillRect(x+width-1, y, 1, height, color)
}

func colorWhenReady(team int, ready bool, pulse int) motiongo.Color {
	if ready || pulse < 2 {
		if team == 0 {
			return motiongo.Color(redColor)
		}
		return motiongo.Color(blueColor)
	}
	return motiongo.Black
}

func halvesReady(nowNS int64) bool {
	return halfReady(0, nowNS) && halfReady(1, nowNS)
}

func halfReady(half int, nowNS int64) bool {
	return halfHeld[half] > 0 || (halfGraceUntil[half] > 0 && nowNS <= halfGraceUntil[half])
}

func activeHalves(nowNS int64) int {
	out := 0
	if halfReady(0, nowNS) {
		out++
	}
	if halfReady(1, nowNS) {
		out++
	}
	return out
}

func halfForY(y int) int {
	if y < motiongo.Height/2 {
		return 0
	}
	return 1
}

func speedForDifficulty(value string) (int64, int64) {
	switch value {
	case "easy":
		return defaultIntervalEasy, minIntervalEasy
	case "hard", "expert":
		return defaultIntervalHard, minIntervalHard
	default:
		return defaultIntervalMedium, minIntervalMedium
	}
}

func labelForTeam(team int) string {
	if team < len(players) && players[team].Label != "" {
		return players[team].Label
	}
	if team == 0 {
		return "Rojo"
	}
	return "Azul"
}

func abs(value int) int {
	if value < 0 {
		return -value
	}
	return value
}

func rgbColor(color rgb) motiongo.Color {
	return motiongo.Color("#" + hexByte(color.r) + hexByte(color.g) + hexByte(color.b))
}

func scaleRGB(color rgb, percent int) rgb {
	return rgb{
		r: clamp(color.r*percent/100, 0, 255),
		g: clamp(color.g*percent/100, 0, 255),
		b: clamp(color.b*percent/100, 0, 255),
	}
}

func addRGB(left rgb, right rgb) rgb {
	return rgb{
		r: clamp(left.r+right.r, 0, 255),
		g: clamp(left.g+right.g, 0, 255),
		b: clamp(left.b+right.b, 0, 255),
	}
}

func hexByte(value int) string {
	digits := "0123456789abcdef"
	value = clamp(value, 0, 255)
	return string([]byte{digits[value/16], digits[value%16]})
}

func maxInt(left int, right int) int {
	if left > right {
		return left
	}
	return right
}

func clamp(v int, lo int, hi int) int {
	if v < lo {
		return lo
	}
	if v > hi {
		return hi
	}
	return v
}

func main() {}
`;
