// Code generated by 'make motion-go-seeds' from game-engine/internal/games/authored/nativegames/whackamolego/game.go. DO NOT EDIT.
export const whackAMoleMotionGoSource = String.raw`// Code generated from game-engine/internal/games/authored/nativegames/whackamolego/game.go; edit the engine copy and run 'make motion-go-seeds'.
package main

import "github.com/lobis/motion-levels/packages/motiongo"

const (
	gameDurationNS     = int64(60000000000)
	targetSize         = 2
	targetGap          = 2
	targetBaseLifeNS   = int64(3400000000)
	targetMinLifeNS    = int64(2300000000)
	targetOverlapNS    = int64(1000000000)
	catchUpBonusNS     = int64(2000000000)
	spawnRetryNS       = int64(160000000)
	minSpawnDistanceSq = 25
	maxSpawnDistanceSq = 225
	targetBaseScore    = 4
	targetSpeedBonus   = 8
	hitFlashTicks      = 8
)

type targetState struct {
	player     int
	x          int
	y          int
	bornNS     int64
	deadlineNS int64
	active     bool
}

var players []motiongo.Player
var lobby motiongo.StartPads
var targets [motiongo.MaxStartPadPlayers]targetState
var playerScore [motiongo.MaxStartPadPlayers]int
var nextSpawnNS [motiongo.MaxStartPadPlayers]int64
var lastX [motiongo.MaxStartPadPlayers]int
var lastY [motiongo.MaxStartPadPlayers]int
var hasLast [motiongo.MaxStartPadPlayers]bool
var catchUpNS [motiongo.MaxStartPadPlayers]int64
var hitFlash [motiongo.Width * motiongo.Height]int
var rng uint32
var startedNS int64
var endsNS int64
var finished bool

//export alloc
func gameAlloc(size uint32) uint32 {
	return motiongo.Alloc(size)
}

//export init
func gameInit(ptr uint32, length uint32) uint64 {
	var req motiongo.InitRequest
	_ = motiongo.Decode(ptr, length, &req)
	players = req.Players
	if len(players) > motiongo.MaxStartPadPlayers {
		players = players[:motiongo.MaxStartPadPlayers]
	}
	if len(players) == 0 {
		players = []motiongo.Player{{Index: 0, Label: "Red", Color: string(motiongo.Red)}}
	}
	rng = uint32(req.Seed)
	if rng == 0 {
		rng = uint32(req.NowUnixNS)
	}
	lobby.Reset(len(players), motiongo.DefaultStartPadSize, motiongo.DefaultStartPadHoldNS, motiongo.DefaultStartCountdownNS, rng)
	startedNS = 0
	endsNS = 0
	finished = false
	for i := 0; i < motiongo.MaxStartPadPlayers; i++ {
		targets[i] = targetState{}
		playerScore[i] = 0
		nextSpawnNS[i] = 0
		catchUpNS[i] = 0
		hasLast[i] = false
	}
	for i := 0; i < len(hitFlash); i++ {
		hitFlash[i] = 0
	}
	initializeStartPositions(0)
	return motiongo.Respond([]motiongo.Event{})
}

//export press
func gamePress(ptr uint32, length uint32) uint64 {
	var req motiongo.PressRequest
	_ = motiongo.Decode(ptr, length, &req)
	tick(req.NowUnixNS)
	if finished {
		return motiongo.Respond([]motiongo.Event{})
	}
	if lobby.AwaitingPlayers() || lobby.InCountdown(req.NowUnixNS) {
		wasAwaiting := lobby.AwaitingPlayers()
		started := lobby.Press(req.X, req.Y, req.Pressed, req.NowUnixNS)
		if wasAwaiting && started {
			startedNS = lobby.StartNS
			endsNS = startedNS + gameDurationNS
			initializeStartPositions(startedNS)
			return motiongo.Respond([]motiongo.Event{{Cue: "start", Message: "starting"}})
		}
		return motiongo.Respond([]motiongo.Event{})
	}
	if !req.Pressed {
		return motiongo.Respond([]motiongo.Event{})
	}
	if expireGame(req.NowUnixNS) {
		return motiongo.Respond([]motiongo.Event{{Cue: "win", Message: "time up"}})
	}
	for i := 0; i < len(players); i++ {
		if targets[i].active && targetContains(targets[i], req.X, req.Y) && req.NowUnixNS < targets[i].deadlineNS {
			points := hitTarget(i, req.NowUnixNS)
			return motiongo.Respond([]motiongo.Event{{Cue: "hit", Message: players[targets[i].player].Label + " +" + itoa(points)}})
		}
	}
	return motiongo.Respond([]motiongo.Event{{Cue: "miss", Message: "miss"}})
}

//export tick
func gameTick(ptr uint32, length uint32) uint64 {
	var req motiongo.TimeRequest
	_ = motiongo.Decode(ptr, length, &req)
	tick(req.NowUnixNS)
	return 0
}

//export render
func gameRender(ptr uint32, length uint32) uint64 {
	var req motiongo.TimeRequest
	_ = motiongo.Decode(ptr, length, &req)
	tick(req.NowUnixNS)
	frame := motiongo.NewFrame(motiongo.Black)
	colors := playerColors()
	for y := 0; y < motiongo.Height; y++ {
		for x := 0; x < motiongo.Width; x++ {
			frame.Set(x, y, colorAt(x, y, req.NowUnixNS, colors))
		}
	}
	return motiongo.Respond(frame)
}

//export snapshot
func gameSnapshot(ptr uint32, length uint32) uint64 {
	var req motiongo.TimeRequest
	_ = motiongo.Decode(ptr, length, &req)
	tick(req.NowUnixNS)
	phase := lobby.Phase(req.NowUnixNS)
	if finished {
		phase = "finished"
	}
	elapsed := int64(0)
	remaining := int64(0)
	if startedNS > 0 && req.NowUnixNS > startedNS {
		elapsed = (req.NowUnixNS - startedNS) / 1000000
	}
	if endsNS > 0 && req.NowUnixNS < endsNS {
		remaining = (endsNS - req.NowUnixNS) / 1000000
	}
	score := totalScore()
	snapPlayers := make([]motiongo.PlayerSnapshot, 0, len(players))
	for i, player := range players {
		snapPlayers = append(snapPlayers, motiongo.PlayerSnapshot{
			Index: i,
			Label: player.Label,
			Color: player.Color,
			Score: playerScore[i],
			Lives: -1,
		})
	}
	return motiongo.Respond(motiongo.Snapshot{
		Phase:           phase,
		Score:           score,
		StartedUnix:     startedNS / 1000000000,
		EndsUnix:        endsNS / 1000000000,
		ElapsedMillis:   elapsed,
		RemainingMillis: remaining,
		CountdownMillis: lobby.CountdownMillis(req.NowUnixNS),
		ActiveTargets:   activeTargetCount(),
		Lives:           -1,
		Success:         true,
		Players:         snapPlayers,
	})
}

func tick(nowNS int64) {
	decayFlashes()
	if finished || !lobby.Running(nowNS) {
		return
	}
	if expireGame(nowNS) {
		return
	}
	expireTargets(nowNS)
	for player := 0; player < len(players); player++ {
		if nowNS >= nextSpawnNS[player] {
			spawnTarget(player, nowNS)
		}
	}
}

func colorAt(x int, y int, nowNS int64, colors []string) motiongo.Color {
	if lobby.AwaitingPlayers() || lobby.InCountdown(nowNS) {
		return lobby.ColorAt(x, y, nowNS, colors)
	}
	index := y*motiongo.Width + x
	if hitFlash[index] > 0 {
		value := 255 * hitFlash[index] / hitFlashTicks
		return motiongo.ScaleHexColor("#ffffff", value*100/255)
	}
	for i := 0; i < len(players); i++ {
		target := targets[i]
		if target.active && targetContains(target, x, y) {
			return targetColor(target, nowNS)
		}
	}
	if finished {
		if (nowNS/200000000)%2 == 0 {
			return motiongo.Color("#24323a")
		}
		return motiongo.Color("#06090b")
	}
	return motiongo.Black
}

func initializeStartPositions(firstSpawnNS int64) {
	for player := 0; player < len(players); player++ {
		origin := lobby.Origin(player)
		lastX[player] = origin.X
		lastY[player] = origin.Y
		hasLast[player] = true
		nextSpawnNS[player] = firstSpawnNS
	}
}

func hitTarget(index int, nowNS int64) int {
	target := targets[index]
	points := targetScore(target, nowNS)
	playerScore[target.player] += points
	for dy := 0; dy < targetSize; dy++ {
		for dx := 0; dx < targetSize; dx++ {
			x := target.x + dx
			y := target.y + dy
			if inBounds(x, y) {
				hitFlash[y*motiongo.Width+x] = hitFlashTicks
			}
		}
	}
	targets[index].active = false
	spawnTarget(target.player, nowNS)
	return points
}

func expireGame(nowNS int64) bool {
	if endsNS == 0 || nowNS < endsNS {
		return false
	}
	finished = true
	for i := 0; i < len(targets); i++ {
		targets[i].active = false
	}
	return true
}

func expireTargets(nowNS int64) {
	for i := 0; i < len(players); i++ {
		if targets[i].active && nowNS >= targets[i].deadlineNS {
			catchUpNS[targets[i].player] = catchUpBonusNS
			targets[i].active = false
		}
	}
}

func spawnTarget(player int, nowNS int64) {
	x, y, ok := pickTargetOrigin(player)
	if !ok {
		nextSpawnNS[player] = nowNS + spawnRetryNS
		return
	}
	interval := targetInterval(nowNS - startedNS)
	life := interval + targetOverlapNS + catchUpNS[player]
	catchUpNS[player] = 0
	nextSpawnNS[player] = nowNS + interval
	lastX[player] = x
	lastY[player] = y
	hasLast[player] = true
	targets[player] = targetState{
		player:     player,
		x:          x,
		y:          y,
		bornNS:     nowNS,
		deadlineNS: nowNS + life,
		active:     true,
	}
}

func pickTargetOrigin(player int) (int, int, bool) {
	bestX := 0
	bestY := 0
	count := 0
	fallbackX := 0
	fallbackY := 0
	fallbackCount := 0
	for y := 0; y <= motiongo.Height-targetSize; y++ {
		for x := 0; x <= motiongo.Width-targetSize; x++ {
			if targetTooClose(x, y) {
				continue
			}
			fallbackCount++
			if int(nextRand()%uint32(fallbackCount)) == 0 {
				fallbackX = x
				fallbackY = y
			}
			if hasLast[player] {
				d2 := distanceSq(x, y, lastX[player], lastY[player])
				if d2 < minSpawnDistanceSq || d2 > maxSpawnDistanceSq {
					continue
				}
			}
			count++
			if int(nextRand()%uint32(count)) == 0 {
				bestX = x
				bestY = y
			}
		}
	}
	if count > 0 {
		return bestX, bestY, true
	}
	if fallbackCount > 0 {
		return fallbackX, fallbackY, true
	}
	return 0, 0, false
}

func targetTooClose(x int, y int) bool {
	for i := 0; i < len(players); i++ {
		target := targets[i]
		if !target.active {
			continue
		}
		if abs(x-target.x) < targetSize+targetGap && abs(y-target.y) < targetSize+targetGap {
			return true
		}
	}
	return false
}

func targetInterval(elapsedNS int64) int64 {
	if elapsedNS < 0 {
		elapsedNS = 0
	}
	if elapsedNS > gameDurationNS {
		elapsedNS = gameDurationNS
	}
	base := targetBaseLifeNS - targetOverlapNS
	drop := targetBaseLifeNS - targetMinLifeNS
	return base - elapsedNS*drop/gameDurationNS
}

func targetContains(target targetState, x int, y int) bool {
	return x >= target.x && x < target.x+targetSize && y >= target.y && y < target.y+targetSize
}

func targetScore(target targetState, nowNS int64) int {
	total := target.deadlineNS - target.bornNS
	if total <= 0 {
		return targetBaseScore
	}
	remaining := target.deadlineNS - nowNS
	if remaining < 0 {
		remaining = 0
	}
	return targetBaseScore + int((remaining*targetSpeedBonus+total-1)/total)
}

func targetColor(target targetState, nowNS int64) motiongo.Color {
	total := target.deadlineNS - target.bornNS
	if total <= 0 {
		return motiongo.Black
	}
	remaining := target.deadlineNS - nowNS
	if remaining <= 0 {
		return motiongo.Black
	}
	percent := int(remaining * 100 / total)
	if remaining < 1000000000 {
		percent = percent * int(remaining/10000000) / 100
	}
	return motiongo.ScaleHexColor(players[target.player].Color, percent)
}

func decayFlashes() {
	for i := 0; i < len(hitFlash); i++ {
		if hitFlash[i] > 0 {
			hitFlash[i]--
		}
	}
}

func playerColors() []string {
	colors := make([]string, 0, len(players))
	for _, player := range players {
		colors = append(colors, player.Color)
	}
	return colors
}

func activeTargetCount() int {
	count := 0
	for i := 0; i < len(players); i++ {
		if targets[i].active {
			count++
		}
	}
	return count
}

func totalScore() int {
	score := 0
	for i := 0; i < len(players); i++ {
		score += playerScore[i]
	}
	return score
}

func inBounds(x int, y int) bool {
	return x >= 0 && x < motiongo.Width && y >= 0 && y < motiongo.Height
}

func distanceSq(ax int, ay int, bx int, by int) int {
	dx := ax - bx
	dy := ay - by
	return dx*dx + dy*dy
}

func abs(value int) int {
	if value < 0 {
		return -value
	}
	return value
}

func nextRand() uint32 {
	rng = rng*1664525 + 1013904223
	return rng
}

func itoa(value int) string {
	if value == 0 {
		return "0"
	}
	buf := [12]byte{}
	i := len(buf)
	n := value
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n = n / 10
	}
	return string(buf[i:])
}

func main() {}
`;
