// Package seedgen generates the platform motion-go seed files from the native
// game sources embedded in the engine.
//
// The engine copy under nativegames/<pkg>/game.go is the source of truth for a
// motion-go game. The platform seed under platform/app/src/lib/seed/<file> is
// derived from it: same gameplay code with the package clause rewritten to
// package main and a func main stub appended, wrapped in a TypeScript export.
// Run "make motion-go-seeds" (go run ./game-engine/cmd/motion-go-seeds) after
// editing a native game; tests fail when a generated seed is stale.
//
// patronesgo and saltosgo are not generated: their native runners are adapters
// over the built-in engines, so their seeds are maintained by hand.
package seedgen

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

type Seed struct {
	// Pkg is the nativegames package directory holding game.go.
	Pkg string
	// SeedFile is the file name under platform/app/src/lib/seed.
	SeedFile string
	// ExportName is the TypeScript export const holding the Go source.
	ExportName string
}

var Seeds = []Seed{
	{Pkg: "duelgo", SeedFile: "duelMotionGo.ts", ExportName: "duelMotionGoSource"},
	{Pkg: "lavago", SeedFile: "lavaMotionGo.ts", ExportName: "lavaMotionGoSource"},
	{Pkg: "memorychallengego", SeedFile: "memoryChallengeMotionGo.ts", ExportName: "memoryChallengeMotionGoSource"},
	{Pkg: "pingpongmotion", SeedFile: "pingPongMotionGo.ts", ExportName: "pingPongMotionGoSource"},
	{Pkg: "tetris", SeedFile: "tetrisMotionGo.ts", ExportName: "tetrisMotionGoSource"},
	{Pkg: "whackamolego", SeedFile: "whackAMoleMotionGo.ts", ExportName: "whackAMoleMotionGoSource"},
}

// HandwrittenSeedFiles are seed sources that have no generated engine
// counterpart; they still must satisfy the motion-go contract and compile.
var HandwrittenSeedFiles = []string{
	"patronesMotionGo.ts",
	"saltosMotionGo.ts",
}

// allowedSeedImports mirrors the platform validator's import allowlist
// (platform/app/src/lib/motionGo.ts); generation fails early when an engine
// game uses an import the editor would reject.
var allowedSeedImports = map[string]bool{
	"encoding/json": true,
	"math":          true,
	"github.com/lobis/motion-levels/packages/motiongo": true,
}

// bannedSeedFragments mirrors the platform validator's banned constructs.
var bannedSeedFragments = []string{"go func", "select {", "for {"}

func NativePath(repoRoot string, seed Seed) string {
	return filepath.Join(repoRoot, "game-engine", "internal", "games", "authored", "nativegames", seed.Pkg, "game.go")
}

func SeedPath(repoRoot string, seedFile string) string {
	return filepath.Join(repoRoot, "platform", "app", "src", "lib", "seed", seedFile)
}

// Generate produces the TypeScript seed file content for one game from its
// native engine source.
func Generate(repoRoot string, seed Seed) ([]byte, error) {
	native, err := os.ReadFile(NativePath(repoRoot, seed))
	if err != nil {
		return nil, err
	}
	goSource, err := SeedGoSource(string(native), seed)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", seed.Pkg, err)
	}
	header := fmt.Sprintf("// Code generated by 'make motion-go-seeds' from game-engine/internal/games/authored/nativegames/%s/game.go. DO NOT EDIT.\n", seed.Pkg)
	return []byte(header + "export const " + seed.ExportName + " = String.raw`" + goSource + "`;\n"), nil
}

// SeedGoSource rewrites a native game source into the standalone package main
// form stored in the seed and compiled to WASM by TinyGo.
func SeedGoSource(native string, seed Seed) (string, error) {
	lines := strings.Split(native, "\n")
	start := 0
	for start < len(lines) {
		trimmed := strings.TrimSpace(lines[start])
		if trimmed == "" || strings.HasPrefix(trimmed, "//") {
			start++
			continue
		}
		break
	}
	if start >= len(lines) || strings.TrimSpace(lines[start]) != "package "+seed.Pkg {
		return "", fmt.Errorf("expected package %s clause after the header comment", seed.Pkg)
	}
	body := strings.Join(lines[start+1:], "\n")
	code := "// Code generated from game-engine/internal/games/authored/nativegames/" + seed.Pkg + "/game.go; edit the engine copy and run 'make motion-go-seeds'.\n" +
		"package main\n" + body
	if !strings.HasSuffix(code, "\n") {
		code += "\n"
	}
	code += "\nfunc main() {}\n"
	if err := CheckSeedContract(code); err != nil {
		return "", err
	}
	if _, err := format.Source([]byte(code)); err != nil {
		return "", fmt.Errorf("generated seed does not parse as Go: %w", err)
	}
	return code, nil
}

// CheckSeedContract rejects code the platform motion-go validator or the
// String.raw embedding cannot handle.
func CheckSeedContract(code string) error {
	if strings.Contains(code, "`") {
		return fmt.Errorf("seed code must not contain backticks (breaks String.raw embedding)")
	}
	if strings.Contains(code, "${") {
		return fmt.Errorf("seed code must not contain ${ (breaks String.raw embedding)")
	}
	for _, fragment := range bannedSeedFragments {
		if strings.Contains(code, fragment) {
			return fmt.Errorf("seed code contains banned construct %q", fragment)
		}
	}
	for _, imported := range importedPackages(code) {
		if !allowedSeedImports[imported] {
			return fmt.Errorf("seed code imports %q, which the motion-go editor rejects", imported)
		}
	}
	return nil
}

// ExtractSeedGoSource returns the Go code embedded in a seed .ts file.
func ExtractSeedGoSource(tsContent string) (string, error) {
	begin := strings.Index(tsContent, "String.raw`")
	end := strings.LastIndex(tsContent, "`")
	if begin < 0 || end <= begin {
		return "", fmt.Errorf("no String.raw backtick block found")
	}
	return tsContent[begin+len("String.raw`") : end], nil
}

func importedPackages(code string) []string {
	out := []string{}
	lines := strings.Split(code, "\n")
	inBlock := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(trimmed, "import ("):
			inBlock = true
		case inBlock && trimmed == ")":
			inBlock = false
		case inBlock && trimmed != "":
			out = append(out, strings.Trim(trimmed, `"`))
		case strings.HasPrefix(trimmed, `import "`):
			out = append(out, strings.Trim(strings.TrimPrefix(trimmed, "import "), `"`))
		}
	}
	return out
}
