import type { PlayerExperienceState } from "@motion-levels/core";

export function playerState(revision = 1): PlayerExperienceState {
  return {
    contractVersion: 1,
    revision,
    runId: "67aec045-60c0-4209-8c03-1558d788b8f5",
    lifecycle: "running",
    allowedControls: ["pause", "restart", "exit", "narration", "mute", "toggle_mute"],
    currentGame: "motion-levels-games:lava",
    venueSessionId: "",
    sessionId: "67aec045-60c0-4209-8c03-1558d788b8f5",
    label: "Lava",
    phase: "running",
    difficulty: "normal",
    teamName: "",
    playerCount: 1,
    players: [],
    score: 0,
    lives: 3,
    music: "",
    musicVolume: 1,
    audioEnabled: true,
    audioMuted: false,
    paused: false,
    success: false,
    startedUnix: 1,
    endsUnix: 0,
    elapsedMillis: 0,
    remainingMillis: 60_000,
    introRemainingMillis: 0,
    countdownRemainingMillis: 0,
    activeTargets: 0,
    lastEventUnixNanos: 0,
    lastEventCue: "",
    lastEventMessage: "",
    lastPressureUnix: 0,
    catalog: [],
  };
}
