// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: packages/contracts/replaypb/replay.proto

package replaypb

import (
	gamepb "github.com/lobis/motion-levels/packages/contracts/gamepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplayRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	VenueSessionId string                 `protobuf:"bytes,2,opt,name=venue_session_id,json=venueSessionId,proto3" json:"venue_session_id,omitempty"`
	Sequence       uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	UnixNanos      int64                  `protobuf:"varint,4,opt,name=unix_nanos,json=unixNanos,proto3" json:"unix_nanos,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ReplayRecord_Header
	//	*ReplayRecord_GameRecord
	//	*ReplayRecord_FloorFrame
	//	*ReplayRecord_Footer
	Payload       isReplayRecord_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayRecord) Reset() {
	*x = ReplayRecord{}
	mi := &file_packages_contracts_replaypb_replay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayRecord) ProtoMessage() {}

func (x *ReplayRecord) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_replaypb_replay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayRecord.ProtoReflect.Descriptor instead.
func (*ReplayRecord) Descriptor() ([]byte, []int) {
	return file_packages_contracts_replaypb_replay_proto_rawDescGZIP(), []int{0}
}

func (x *ReplayRecord) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReplayRecord) GetVenueSessionId() string {
	if x != nil {
		return x.VenueSessionId
	}
	return ""
}

func (x *ReplayRecord) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ReplayRecord) GetUnixNanos() int64 {
	if x != nil {
		return x.UnixNanos
	}
	return 0
}

func (x *ReplayRecord) GetPayload() isReplayRecord_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ReplayRecord) GetHeader() *ReplayHeader {
	if x != nil {
		if x, ok := x.Payload.(*ReplayRecord_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *ReplayRecord) GetGameRecord() *gamepb.GameSessionRecord {
	if x != nil {
		if x, ok := x.Payload.(*ReplayRecord_GameRecord); ok {
			return x.GameRecord
		}
	}
	return nil
}

func (x *ReplayRecord) GetFloorFrame() *FloorFrame {
	if x != nil {
		if x, ok := x.Payload.(*ReplayRecord_FloorFrame); ok {
			return x.FloorFrame
		}
	}
	return nil
}

func (x *ReplayRecord) GetFooter() *ReplayFooter {
	if x != nil {
		if x, ok := x.Payload.(*ReplayRecord_Footer); ok {
			return x.Footer
		}
	}
	return nil
}

type isReplayRecord_Payload interface {
	isReplayRecord_Payload()
}

type ReplayRecord_Header struct {
	Header *ReplayHeader `protobuf:"bytes,10,opt,name=header,proto3,oneof"`
}

type ReplayRecord_GameRecord struct {
	GameRecord *gamepb.GameSessionRecord `protobuf:"bytes,11,opt,name=game_record,json=gameRecord,proto3,oneof"`
}

type ReplayRecord_FloorFrame struct {
	FloorFrame *FloorFrame `protobuf:"bytes,12,opt,name=floor_frame,json=floorFrame,proto3,oneof"`
}

type ReplayRecord_Footer struct {
	Footer *ReplayFooter `protobuf:"bytes,13,opt,name=footer,proto3,oneof"`
}

func (*ReplayRecord_Header) isReplayRecord_Payload() {}

func (*ReplayRecord_GameRecord) isReplayRecord_Payload() {}

func (*ReplayRecord_FloorFrame) isReplayRecord_Payload() {}

func (*ReplayRecord_Footer) isReplayRecord_Payload() {}

type ReplayHeader struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ControllerId     string                 `protobuf:"bytes,2,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`
	Game             string                 `protobuf:"bytes,3,opt,name=game,proto3" json:"game,omitempty"`
	Label            string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	TeamName         string                 `protobuf:"bytes,5,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	StartedUnixNanos int64                  `protobuf:"varint,6,opt,name=started_unix_nanos,json=startedUnixNanos,proto3" json:"started_unix_nanos,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReplayHeader) Reset() {
	*x = ReplayHeader{}
	mi := &file_packages_contracts_replaypb_replay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayHeader) ProtoMessage() {}

func (x *ReplayHeader) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_replaypb_replay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayHeader.ProtoReflect.Descriptor instead.
func (*ReplayHeader) Descriptor() ([]byte, []int) {
	return file_packages_contracts_replaypb_replay_proto_rawDescGZIP(), []int{1}
}

func (x *ReplayHeader) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ReplayHeader) GetControllerId() string {
	if x != nil {
		return x.ControllerId
	}
	return ""
}

func (x *ReplayHeader) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *ReplayHeader) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ReplayHeader) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *ReplayHeader) GetStartedUnixNanos() int64 {
	if x != nil {
		return x.StartedUnixNanos
	}
	return 0
}

type ReplayFooter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Reason         string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	EndedUnixNanos int64                  `protobuf:"varint,2,opt,name=ended_unix_nanos,json=endedUnixNanos,proto3" json:"ended_unix_nanos,omitempty"`
	FrameCount     uint64                 `protobuf:"varint,3,opt,name=frame_count,json=frameCount,proto3" json:"frame_count,omitempty"`
	EventCount     uint64                 `protobuf:"varint,4,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplayFooter) Reset() {
	*x = ReplayFooter{}
	mi := &file_packages_contracts_replaypb_replay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayFooter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayFooter) ProtoMessage() {}

func (x *ReplayFooter) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_replaypb_replay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayFooter.ProtoReflect.Descriptor instead.
func (*ReplayFooter) Descriptor() ([]byte, []int) {
	return file_packages_contracts_replaypb_replay_proto_rawDescGZIP(), []int{2}
}

func (x *ReplayFooter) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReplayFooter) GetEndedUnixNanos() int64 {
	if x != nil {
		return x.EndedUnixNanos
	}
	return 0
}

func (x *ReplayFooter) GetFrameCount() uint64 {
	if x != nil {
		return x.FrameCount
	}
	return 0
}

func (x *ReplayFooter) GetEventCount() uint64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

type FloorFrame struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	Width                        uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height                       uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Keyframe                     bool                   `protobuf:"varint,3,opt,name=keyframe,proto3" json:"keyframe,omitempty"`
	ControllerSequence           uint64                 `protobuf:"varint,4,opt,name=controller_sequence,json=controllerSequence,proto3" json:"controller_sequence,omitempty"`
	GameFrameSequence            uint64                 `protobuf:"varint,5,opt,name=game_frame_sequence,json=gameFrameSequence,proto3" json:"game_frame_sequence,omitempty"`
	GameUnixNanos                int64                  `protobuf:"varint,6,opt,name=game_unix_nanos,json=gameUnixNanos,proto3" json:"game_unix_nanos,omitempty"`
	ControllerReceivedUnixNanos  int64                  `protobuf:"varint,7,opt,name=controller_received_unix_nanos,json=controllerReceivedUnixNanos,proto3" json:"controller_received_unix_nanos,omitempty"`
	ControllerPresentedUnixNanos int64                  `protobuf:"varint,8,opt,name=controller_presented_unix_nanos,json=controllerPresentedUnixNanos,proto3" json:"controller_presented_unix_nanos,omitempty"`
	Tiles                        []*TileDelta           `protobuf:"bytes,9,rep,name=tiles,proto3" json:"tiles,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *FloorFrame) Reset() {
	*x = FloorFrame{}
	mi := &file_packages_contracts_replaypb_replay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloorFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloorFrame) ProtoMessage() {}

func (x *FloorFrame) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_replaypb_replay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloorFrame.ProtoReflect.Descriptor instead.
func (*FloorFrame) Descriptor() ([]byte, []int) {
	return file_packages_contracts_replaypb_replay_proto_rawDescGZIP(), []int{3}
}

func (x *FloorFrame) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *FloorFrame) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FloorFrame) GetKeyframe() bool {
	if x != nil {
		return x.Keyframe
	}
	return false
}

func (x *FloorFrame) GetControllerSequence() uint64 {
	if x != nil {
		return x.ControllerSequence
	}
	return 0
}

func (x *FloorFrame) GetGameFrameSequence() uint64 {
	if x != nil {
		return x.GameFrameSequence
	}
	return 0
}

func (x *FloorFrame) GetGameUnixNanos() int64 {
	if x != nil {
		return x.GameUnixNanos
	}
	return 0
}

func (x *FloorFrame) GetControllerReceivedUnixNanos() int64 {
	if x != nil {
		return x.ControllerReceivedUnixNanos
	}
	return 0
}

func (x *FloorFrame) GetControllerPresentedUnixNanos() int64 {
	if x != nil {
		return x.ControllerPresentedUnixNanos
	}
	return 0
}

func (x *FloorFrame) GetTiles() []*TileDelta {
	if x != nil {
		return x.Tiles
	}
	return nil
}

type TileDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	R             uint32                 `protobuf:"varint,2,opt,name=r,proto3" json:"r,omitempty"`
	G             uint32                 `protobuf:"varint,3,opt,name=g,proto3" json:"g,omitempty"`
	B             uint32                 `protobuf:"varint,4,opt,name=b,proto3" json:"b,omitempty"`
	Pressed       bool                   `protobuf:"varint,5,opt,name=pressed,proto3" json:"pressed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TileDelta) Reset() {
	*x = TileDelta{}
	mi := &file_packages_contracts_replaypb_replay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TileDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TileDelta) ProtoMessage() {}

func (x *TileDelta) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_replaypb_replay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TileDelta.ProtoReflect.Descriptor instead.
func (*TileDelta) Descriptor() ([]byte, []int) {
	return file_packages_contracts_replaypb_replay_proto_rawDescGZIP(), []int{4}
}

func (x *TileDelta) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *TileDelta) GetR() uint32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *TileDelta) GetG() uint32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *TileDelta) GetB() uint32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *TileDelta) GetPressed() bool {
	if x != nil {
		return x.Pressed
	}
	return false
}

var File_packages_contracts_replaypb_replay_proto protoreflect.FileDescriptor

const file_packages_contracts_replaypb_replay_proto_rawDesc = "" +
	"\n" +
	"(packages/contracts/replaypb/replay.proto\x12\x1dmotionlevels.engine.replay.v1\x1a$packages/contracts/gamepb/game.proto\"\xcc\x03\n" +
	"\fReplayRecord\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12(\n" +
	"\x10venue_session_id\x18\x02 \x01(\tR\x0evenueSessionId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x1d\n" +
	"\n" +
	"unix_nanos\x18\x04 \x01(\x03R\tunixNanos\x12E\n" +
	"\x06header\x18\n" +
	" \x01(\v2+.motionlevels.engine.replay.v1.ReplayHeaderH\x00R\x06header\x12Q\n" +
	"\vgame_record\x18\v \x01(\v2..motionlevels.engine.game.v1.GameSessionRecordH\x00R\n" +
	"gameRecord\x12L\n" +
	"\vfloor_frame\x18\f \x01(\v2).motionlevels.engine.replay.v1.FloorFrameH\x00R\n" +
	"floorFrame\x12E\n" +
	"\x06footer\x18\r \x01(\v2+.motionlevels.engine.replay.v1.ReplayFooterH\x00R\x06footerB\t\n" +
	"\apayload\"\xc2\x01\n" +
	"\fReplayHeader\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12#\n" +
	"\rcontroller_id\x18\x02 \x01(\tR\fcontrollerId\x12\x12\n" +
	"\x04game\x18\x03 \x01(\tR\x04game\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x1b\n" +
	"\tteam_name\x18\x05 \x01(\tR\bteamName\x12,\n" +
	"\x12started_unix_nanos\x18\x06 \x01(\x03R\x10startedUnixNanos\"\x92\x01\n" +
	"\fReplayFooter\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12(\n" +
	"\x10ended_unix_nanos\x18\x02 \x01(\x03R\x0eendedUnixNanos\x12\x1f\n" +
	"\vframe_count\x18\x03 \x01(\x04R\n" +
	"frameCount\x12\x1f\n" +
	"\vevent_count\x18\x04 \x01(\x04R\n" +
	"eventCount\"\xab\x03\n" +
	"\n" +
	"FloorFrame\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\x12\x1a\n" +
	"\bkeyframe\x18\x03 \x01(\bR\bkeyframe\x12/\n" +
	"\x13controller_sequence\x18\x04 \x01(\x04R\x12controllerSequence\x12.\n" +
	"\x13game_frame_sequence\x18\x05 \x01(\x04R\x11gameFrameSequence\x12&\n" +
	"\x0fgame_unix_nanos\x18\x06 \x01(\x03R\rgameUnixNanos\x12C\n" +
	"\x1econtroller_received_unix_nanos\x18\a \x01(\x03R\x1bcontrollerReceivedUnixNanos\x12E\n" +
	"\x1fcontroller_presented_unix_nanos\x18\b \x01(\x03R\x1ccontrollerPresentedUnixNanos\x12>\n" +
	"\x05tiles\x18\t \x03(\v2(.motionlevels.engine.replay.v1.TileDeltaR\x05tiles\"e\n" +
	"\tTileDelta\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\f\n" +
	"\x01r\x18\x02 \x01(\rR\x01r\x12\f\n" +
	"\x01g\x18\x03 \x01(\rR\x01g\x12\f\n" +
	"\x01b\x18\x04 \x01(\rR\x01b\x12\x18\n" +
	"\apressed\x18\x05 \x01(\bR\apressedB<Z:github.com/lobis/motion-levels/packages/contracts/replaypbb\x06proto3"

var (
	file_packages_contracts_replaypb_replay_proto_rawDescOnce sync.Once
	file_packages_contracts_replaypb_replay_proto_rawDescData []byte
)

func file_packages_contracts_replaypb_replay_proto_rawDescGZIP() []byte {
	file_packages_contracts_replaypb_replay_proto_rawDescOnce.Do(func() {
		file_packages_contracts_replaypb_replay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_contracts_replaypb_replay_proto_rawDesc), len(file_packages_contracts_replaypb_replay_proto_rawDesc)))
	})
	return file_packages_contracts_replaypb_replay_proto_rawDescData
}

var file_packages_contracts_replaypb_replay_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_packages_contracts_replaypb_replay_proto_goTypes = []any{
	(*ReplayRecord)(nil),             // 0: motionlevels.engine.replay.v1.ReplayRecord
	(*ReplayHeader)(nil),             // 1: motionlevels.engine.replay.v1.ReplayHeader
	(*ReplayFooter)(nil),             // 2: motionlevels.engine.replay.v1.ReplayFooter
	(*FloorFrame)(nil),               // 3: motionlevels.engine.replay.v1.FloorFrame
	(*TileDelta)(nil),                // 4: motionlevels.engine.replay.v1.TileDelta
	(*gamepb.GameSessionRecord)(nil), // 5: motionlevels.engine.game.v1.GameSessionRecord
}
var file_packages_contracts_replaypb_replay_proto_depIdxs = []int32{
	1, // 0: motionlevels.engine.replay.v1.ReplayRecord.header:type_name -> motionlevels.engine.replay.v1.ReplayHeader
	5, // 1: motionlevels.engine.replay.v1.ReplayRecord.game_record:type_name -> motionlevels.engine.game.v1.GameSessionRecord
	3, // 2: motionlevels.engine.replay.v1.ReplayRecord.floor_frame:type_name -> motionlevels.engine.replay.v1.FloorFrame
	2, // 3: motionlevels.engine.replay.v1.ReplayRecord.footer:type_name -> motionlevels.engine.replay.v1.ReplayFooter
	4, // 4: motionlevels.engine.replay.v1.FloorFrame.tiles:type_name -> motionlevels.engine.replay.v1.TileDelta
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_packages_contracts_replaypb_replay_proto_init() }
func file_packages_contracts_replaypb_replay_proto_init() {
	if File_packages_contracts_replaypb_replay_proto != nil {
		return
	}
	file_packages_contracts_replaypb_replay_proto_msgTypes[0].OneofWrappers = []any{
		(*ReplayRecord_Header)(nil),
		(*ReplayRecord_GameRecord)(nil),
		(*ReplayRecord_FloorFrame)(nil),
		(*ReplayRecord_Footer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_contracts_replaypb_replay_proto_rawDesc), len(file_packages_contracts_replaypb_replay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packages_contracts_replaypb_replay_proto_goTypes,
		DependencyIndexes: file_packages_contracts_replaypb_replay_proto_depIdxs,
		MessageInfos:      file_packages_contracts_replaypb_replay_proto_msgTypes,
	}.Build()
	File_packages_contracts_replaypb_replay_proto = out.File
	file_packages_contracts_replaypb_replay_proto_goTypes = nil
	file_packages_contracts_replaypb_replay_proto_depIdxs = nil
}
