// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: packages/contracts/gamepb/game.proto

package gamepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameSessionRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sequence       uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	UnixNanos      int64                  `protobuf:"varint,3,opt,name=unix_nanos,json=unixNanos,proto3" json:"unix_nanos,omitempty"`
	VenueSessionId string                 `protobuf:"bytes,4,opt,name=venue_session_id,json=venueSessionId,proto3" json:"venue_session_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GameSessionRecord_SessionStarted
	//	*GameSessionRecord_SessionEnded
	//	*GameSessionRecord_ApiInteraction
	//	*GameSessionRecord_MenuCommand
	//	*GameSessionRecord_PressureInput
	//	*GameSessionRecord_GameEvent
	//	*GameSessionRecord_AudioCue
	//	*GameSessionRecord_DisplaySnapshot
	//	*GameSessionRecord_LevelAttemptStarted
	//	*GameSessionRecord_LevelAttemptFinished
	Payload       isGameSessionRecord_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameSessionRecord) Reset() {
	*x = GameSessionRecord{}
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameSessionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSessionRecord) ProtoMessage() {}

func (x *GameSessionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSessionRecord.ProtoReflect.Descriptor instead.
func (*GameSessionRecord) Descriptor() ([]byte, []int) {
	return file_packages_contracts_gamepb_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameSessionRecord) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GameSessionRecord) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *GameSessionRecord) GetUnixNanos() int64 {
	if x != nil {
		return x.UnixNanos
	}
	return 0
}

func (x *GameSessionRecord) GetVenueSessionId() string {
	if x != nil {
		return x.VenueSessionId
	}
	return ""
}

func (x *GameSessionRecord) GetPayload() isGameSessionRecord_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GameSessionRecord) GetSessionStarted() *SessionStarted {
	if x != nil {
		if x, ok := x.Payload.(*GameSessionRecord_SessionStarted); ok {
			return x.SessionStarted
		}
	}
	return nil
}

func (x *GameSessionRecord) GetSessionEnded() *SessionEnded {
	if x != nil {
		if x, ok := x.Payload.(*GameSessionRecord_SessionEnded); ok {
			return x.SessionEnded
		}
	}
	return nil
}

func (x *GameSessionRecord) GetApiInteraction() *ApiInteraction {
	if x != nil {
		if x, ok := x.Payload.(*GameSessionRecord_ApiInteraction); ok {
			return x.ApiInteraction
		}
	}
	return nil
}

func (x *GameSessionRecord) GetMenuCommand() *MenuCommand {
	if x != nil {
		if x, ok := x.Payload.(*GameSessionRecord_MenuCommand); ok {
			return x.MenuCommand
		}
	}
	return nil
}

func (x *GameSessionRecord) GetPressureInput() *PressureInput {
	if x != nil {
		if x, ok := x.Payload.(*GameSessionRecord_PressureInput); ok {
			return x.PressureInput
		}
	}
	return nil
}

func (x *GameSessionRecord) GetGameEvent() *GameEvent {
	if x != nil {
		if x, ok := x.Payload.(*GameSessionRecord_GameEvent); ok {
			return x.GameEvent
		}
	}
	return nil
}

func (x *GameSessionRecord) GetAudioCue() *AudioCue {
	if x != nil {
		if x, ok := x.Payload.(*GameSessionRecord_AudioCue); ok {
			return x.AudioCue
		}
	}
	return nil
}

func (x *GameSessionRecord) GetDisplaySnapshot() *DisplaySnapshot {
	if x != nil {
		if x, ok := x.Payload.(*GameSessionRecord_DisplaySnapshot); ok {
			return x.DisplaySnapshot
		}
	}
	return nil
}

func (x *GameSessionRecord) GetLevelAttemptStarted() *LevelAttemptStarted {
	if x != nil {
		if x, ok := x.Payload.(*GameSessionRecord_LevelAttemptStarted); ok {
			return x.LevelAttemptStarted
		}
	}
	return nil
}

func (x *GameSessionRecord) GetLevelAttemptFinished() *LevelAttemptFinished {
	if x != nil {
		if x, ok := x.Payload.(*GameSessionRecord_LevelAttemptFinished); ok {
			return x.LevelAttemptFinished
		}
	}
	return nil
}

type isGameSessionRecord_Payload interface {
	isGameSessionRecord_Payload()
}

type GameSessionRecord_SessionStarted struct {
	SessionStarted *SessionStarted `protobuf:"bytes,10,opt,name=session_started,json=sessionStarted,proto3,oneof"`
}

type GameSessionRecord_SessionEnded struct {
	SessionEnded *SessionEnded `protobuf:"bytes,11,opt,name=session_ended,json=sessionEnded,proto3,oneof"`
}

type GameSessionRecord_ApiInteraction struct {
	ApiInteraction *ApiInteraction `protobuf:"bytes,12,opt,name=api_interaction,json=apiInteraction,proto3,oneof"`
}

type GameSessionRecord_MenuCommand struct {
	MenuCommand *MenuCommand `protobuf:"bytes,13,opt,name=menu_command,json=menuCommand,proto3,oneof"`
}

type GameSessionRecord_PressureInput struct {
	PressureInput *PressureInput `protobuf:"bytes,14,opt,name=pressure_input,json=pressureInput,proto3,oneof"`
}

type GameSessionRecord_GameEvent struct {
	GameEvent *GameEvent `protobuf:"bytes,15,opt,name=game_event,json=gameEvent,proto3,oneof"`
}

type GameSessionRecord_AudioCue struct {
	AudioCue *AudioCue `protobuf:"bytes,16,opt,name=audio_cue,json=audioCue,proto3,oneof"`
}

type GameSessionRecord_DisplaySnapshot struct {
	DisplaySnapshot *DisplaySnapshot `protobuf:"bytes,17,opt,name=display_snapshot,json=displaySnapshot,proto3,oneof"`
}

type GameSessionRecord_LevelAttemptStarted struct {
	LevelAttemptStarted *LevelAttemptStarted `protobuf:"bytes,18,opt,name=level_attempt_started,json=levelAttemptStarted,proto3,oneof"`
}

type GameSessionRecord_LevelAttemptFinished struct {
	LevelAttemptFinished *LevelAttemptFinished `protobuf:"bytes,19,opt,name=level_attempt_finished,json=levelAttemptFinished,proto3,oneof"`
}

func (*GameSessionRecord_SessionStarted) isGameSessionRecord_Payload() {}

func (*GameSessionRecord_SessionEnded) isGameSessionRecord_Payload() {}

func (*GameSessionRecord_ApiInteraction) isGameSessionRecord_Payload() {}

func (*GameSessionRecord_MenuCommand) isGameSessionRecord_Payload() {}

func (*GameSessionRecord_PressureInput) isGameSessionRecord_Payload() {}

func (*GameSessionRecord_GameEvent) isGameSessionRecord_Payload() {}

func (*GameSessionRecord_AudioCue) isGameSessionRecord_Payload() {}

func (*GameSessionRecord_DisplaySnapshot) isGameSessionRecord_Payload() {}

func (*GameSessionRecord_LevelAttemptStarted) isGameSessionRecord_Payload() {}

func (*GameSessionRecord_LevelAttemptFinished) isGameSessionRecord_Payload() {}

type SessionStarted struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Game             string                 `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	Label            string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	PlayerCount      uint32                 `protobuf:"varint,3,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	RngSeed          int64                  `protobuf:"varint,4,opt,name=rng_seed,json=rngSeed,proto3" json:"rng_seed,omitempty"`
	StartedUnixNanos int64                  `protobuf:"varint,5,opt,name=started_unix_nanos,json=startedUnixNanos,proto3" json:"started_unix_nanos,omitempty"`
	Difficulty       string                 `protobuf:"bytes,6,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Level            string                 `protobuf:"bytes,7,opt,name=level,proto3" json:"level,omitempty"`
	TeamName         string                 `protobuf:"bytes,8,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	Players          []*DisplayPlayer       `protobuf:"bytes,9,rep,name=players,proto3" json:"players,omitempty"`
	VenueSessionId   string                 `protobuf:"bytes,10,opt,name=venue_session_id,json=venueSessionId,proto3" json:"venue_session_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionStarted) Reset() {
	*x = SessionStarted{}
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStarted) ProtoMessage() {}

func (x *SessionStarted) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStarted.ProtoReflect.Descriptor instead.
func (*SessionStarted) Descriptor() ([]byte, []int) {
	return file_packages_contracts_gamepb_game_proto_rawDescGZIP(), []int{1}
}

func (x *SessionStarted) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *SessionStarted) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SessionStarted) GetPlayerCount() uint32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *SessionStarted) GetRngSeed() int64 {
	if x != nil {
		return x.RngSeed
	}
	return 0
}

func (x *SessionStarted) GetStartedUnixNanos() int64 {
	if x != nil {
		return x.StartedUnixNanos
	}
	return 0
}

func (x *SessionStarted) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *SessionStarted) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *SessionStarted) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *SessionStarted) GetPlayers() []*DisplayPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *SessionStarted) GetVenueSessionId() string {
	if x != nil {
		return x.VenueSessionId
	}
	return ""
}

type SessionEnded struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Reason         string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	EndedUnixNanos int64                  `protobuf:"varint,2,opt,name=ended_unix_nanos,json=endedUnixNanos,proto3" json:"ended_unix_nanos,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionEnded) Reset() {
	*x = SessionEnded{}
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEnded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEnded) ProtoMessage() {}

func (x *SessionEnded) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEnded.ProtoReflect.Descriptor instead.
func (*SessionEnded) Descriptor() ([]byte, []int) {
	return file_packages_contracts_gamepb_game_proto_rawDescGZIP(), []int{2}
}

func (x *SessionEnded) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SessionEnded) GetEndedUnixNanos() int64 {
	if x != nil {
		return x.EndedUnixNanos
	}
	return 0
}

type ApiInteraction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	RemoteAddr    string                 `protobuf:"bytes,3,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	UnixNanos     int64                  `protobuf:"varint,4,opt,name=unix_nanos,json=unixNanos,proto3" json:"unix_nanos,omitempty"`
	Status        uint32                 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiInteraction) Reset() {
	*x = ApiInteraction{}
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiInteraction) ProtoMessage() {}

func (x *ApiInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiInteraction.ProtoReflect.Descriptor instead.
func (*ApiInteraction) Descriptor() ([]byte, []int) {
	return file_packages_contracts_gamepb_game_proto_rawDescGZIP(), []int{3}
}

func (x *ApiInteraction) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ApiInteraction) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ApiInteraction) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *ApiInteraction) GetUnixNanos() int64 {
	if x != nil {
		return x.UnixNanos
	}
	return 0
}

func (x *ApiInteraction) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type MenuCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Game          string                 `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	PlayerCount   uint32                 `protobuf:"varint,3,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	UnixNanos     int64                  `protobuf:"varint,4,opt,name=unix_nanos,json=unixNanos,proto3" json:"unix_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuCommand) Reset() {
	*x = MenuCommand{}
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuCommand) ProtoMessage() {}

func (x *MenuCommand) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuCommand.ProtoReflect.Descriptor instead.
func (*MenuCommand) Descriptor() ([]byte, []int) {
	return file_packages_contracts_gamepb_game_proto_rawDescGZIP(), []int{4}
}

func (x *MenuCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *MenuCommand) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *MenuCommand) GetPlayerCount() uint32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *MenuCommand) GetUnixNanos() int64 {
	if x != nil {
		return x.UnixNanos
	}
	return 0
}

type PressureInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceSequence uint64                 `protobuf:"varint,1,opt,name=source_sequence,json=sourceSequence,proto3" json:"source_sequence,omitempty"`
	UnixNanos      int64                  `protobuf:"varint,2,opt,name=unix_nanos,json=unixNanos,proto3" json:"unix_nanos,omitempty"`
	X              uint32                 `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y              uint32                 `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Pressed        bool                   `protobuf:"varint,5,opt,name=pressed,proto3" json:"pressed,omitempty"`
	Source         string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Controller     uint32                 `protobuf:"varint,7,opt,name=controller,proto3" json:"controller,omitempty"`
	Channel        uint32                 `protobuf:"varint,8,opt,name=channel,proto3" json:"channel,omitempty"`
	Position       uint32                 `protobuf:"varint,9,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PressureInput) Reset() {
	*x = PressureInput{}
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PressureInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PressureInput) ProtoMessage() {}

func (x *PressureInput) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PressureInput.ProtoReflect.Descriptor instead.
func (*PressureInput) Descriptor() ([]byte, []int) {
	return file_packages_contracts_gamepb_game_proto_rawDescGZIP(), []int{5}
}

func (x *PressureInput) GetSourceSequence() uint64 {
	if x != nil {
		return x.SourceSequence
	}
	return 0
}

func (x *PressureInput) GetUnixNanos() int64 {
	if x != nil {
		return x.UnixNanos
	}
	return 0
}

func (x *PressureInput) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PressureInput) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PressureInput) GetPressed() bool {
	if x != nil {
		return x.Pressed
	}
	return false
}

func (x *PressureInput) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PressureInput) GetController() uint32 {
	if x != nil {
		return x.Controller
	}
	return 0
}

func (x *PressureInput) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *PressureInput) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type GameEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cue           string                 `protobuf:"bytes,1,opt,name=cue,proto3" json:"cue,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UnixNanos     int64                  `protobuf:"varint,3,opt,name=unix_nanos,json=unixNanos,proto3" json:"unix_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_packages_contracts_gamepb_game_proto_rawDescGZIP(), []int{6}
}

func (x *GameEvent) GetCue() string {
	if x != nil {
		return x.Cue
	}
	return ""
}

func (x *GameEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GameEvent) GetUnixNanos() int64 {
	if x != nil {
		return x.UnixNanos
	}
	return 0
}

type AudioCue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Cue           string                 `protobuf:"bytes,2,opt,name=cue,proto3" json:"cue,omitempty"`
	Volume        float64                `protobuf:"fixed64,3,opt,name=volume,proto3" json:"volume,omitempty"`
	UnixNanos     int64                  `protobuf:"varint,4,opt,name=unix_nanos,json=unixNanos,proto3" json:"unix_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioCue) Reset() {
	*x = AudioCue{}
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioCue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioCue) ProtoMessage() {}

func (x *AudioCue) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioCue.ProtoReflect.Descriptor instead.
func (*AudioCue) Descriptor() ([]byte, []int) {
	return file_packages_contracts_gamepb_game_proto_rawDescGZIP(), []int{7}
}

func (x *AudioCue) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *AudioCue) GetCue() string {
	if x != nil {
		return x.Cue
	}
	return ""
}

func (x *AudioCue) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *AudioCue) GetUnixNanos() int64 {
	if x != nil {
		return x.UnixNanos
	}
	return 0
}

type LevelAttemptStarted struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	AttemptId                string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Game                     string                 `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	LevelId                  string                 `protobuf:"bytes,3,opt,name=level_id,json=levelId,proto3" json:"level_id,omitempty"`
	LevelNumber              uint32                 `protobuf:"varint,4,opt,name=level_number,json=levelNumber,proto3" json:"level_number,omitempty"`
	Difficulty               string                 `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	PlayerCount              uint32                 `protobuf:"varint,6,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	LivesStart               int32                  `protobuf:"varint,7,opt,name=lives_start,json=livesStart,proto3" json:"lives_start,omitempty"`
	ScoreStart               int32                  `protobuf:"varint,8,opt,name=score_start,json=scoreStart,proto3" json:"score_start,omitempty"`
	ActiveTargetsStart       uint32                 `protobuf:"varint,9,opt,name=active_targets_start,json=activeTargetsStart,proto3" json:"active_targets_start,omitempty"`
	StartedUnixNanos         int64                  `protobuf:"varint,10,opt,name=started_unix_nanos,json=startedUnixNanos,proto3" json:"started_unix_nanos,omitempty"`
	GameplayStartedUnixNanos int64                  `protobuf:"varint,11,opt,name=gameplay_started_unix_nanos,json=gameplayStartedUnixNanos,proto3" json:"gameplay_started_unix_nanos,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *LevelAttemptStarted) Reset() {
	*x = LevelAttemptStarted{}
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelAttemptStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelAttemptStarted) ProtoMessage() {}

func (x *LevelAttemptStarted) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelAttemptStarted.ProtoReflect.Descriptor instead.
func (*LevelAttemptStarted) Descriptor() ([]byte, []int) {
	return file_packages_contracts_gamepb_game_proto_rawDescGZIP(), []int{8}
}

func (x *LevelAttemptStarted) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *LevelAttemptStarted) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *LevelAttemptStarted) GetLevelId() string {
	if x != nil {
		return x.LevelId
	}
	return ""
}

func (x *LevelAttemptStarted) GetLevelNumber() uint32 {
	if x != nil {
		return x.LevelNumber
	}
	return 0
}

func (x *LevelAttemptStarted) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *LevelAttemptStarted) GetPlayerCount() uint32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *LevelAttemptStarted) GetLivesStart() int32 {
	if x != nil {
		return x.LivesStart
	}
	return 0
}

func (x *LevelAttemptStarted) GetScoreStart() int32 {
	if x != nil {
		return x.ScoreStart
	}
	return 0
}

func (x *LevelAttemptStarted) GetActiveTargetsStart() uint32 {
	if x != nil {
		return x.ActiveTargetsStart
	}
	return 0
}

func (x *LevelAttemptStarted) GetStartedUnixNanos() int64 {
	if x != nil {
		return x.StartedUnixNanos
	}
	return 0
}

func (x *LevelAttemptStarted) GetGameplayStartedUnixNanos() int64 {
	if x != nil {
		return x.GameplayStartedUnixNanos
	}
	return 0
}

type LevelAttemptFinished struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	AttemptId                string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Game                     string                 `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	LevelId                  string                 `protobuf:"bytes,3,opt,name=level_id,json=levelId,proto3" json:"level_id,omitempty"`
	LevelNumber              uint32                 `protobuf:"varint,4,opt,name=level_number,json=levelNumber,proto3" json:"level_number,omitempty"`
	Difficulty               string                 `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Result                   string                 `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	ScoreStart               int32                  `protobuf:"varint,7,opt,name=score_start,json=scoreStart,proto3" json:"score_start,omitempty"`
	ScoreEnd                 int32                  `protobuf:"varint,8,opt,name=score_end,json=scoreEnd,proto3" json:"score_end,omitempty"`
	LivesStart               int32                  `protobuf:"varint,9,opt,name=lives_start,json=livesStart,proto3" json:"lives_start,omitempty"`
	LivesEnd                 int32                  `protobuf:"varint,10,opt,name=lives_end,json=livesEnd,proto3" json:"lives_end,omitempty"`
	ActiveTargetsStart       uint32                 `protobuf:"varint,11,opt,name=active_targets_start,json=activeTargetsStart,proto3" json:"active_targets_start,omitempty"`
	ActiveTargetsEnd         uint32                 `protobuf:"varint,12,opt,name=active_targets_end,json=activeTargetsEnd,proto3" json:"active_targets_end,omitempty"`
	StartedUnixNanos         int64                  `protobuf:"varint,13,opt,name=started_unix_nanos,json=startedUnixNanos,proto3" json:"started_unix_nanos,omitempty"`
	GameplayStartedUnixNanos int64                  `protobuf:"varint,14,opt,name=gameplay_started_unix_nanos,json=gameplayStartedUnixNanos,proto3" json:"gameplay_started_unix_nanos,omitempty"`
	EndedUnixNanos           int64                  `protobuf:"varint,15,opt,name=ended_unix_nanos,json=endedUnixNanos,proto3" json:"ended_unix_nanos,omitempty"`
	ElapsedMillis            int64                  `protobuf:"varint,16,opt,name=elapsed_millis,json=elapsedMillis,proto3" json:"elapsed_millis,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *LevelAttemptFinished) Reset() {
	*x = LevelAttemptFinished{}
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelAttemptFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelAttemptFinished) ProtoMessage() {}

func (x *LevelAttemptFinished) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelAttemptFinished.ProtoReflect.Descriptor instead.
func (*LevelAttemptFinished) Descriptor() ([]byte, []int) {
	return file_packages_contracts_gamepb_game_proto_rawDescGZIP(), []int{9}
}

func (x *LevelAttemptFinished) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *LevelAttemptFinished) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *LevelAttemptFinished) GetLevelId() string {
	if x != nil {
		return x.LevelId
	}
	return ""
}

func (x *LevelAttemptFinished) GetLevelNumber() uint32 {
	if x != nil {
		return x.LevelNumber
	}
	return 0
}

func (x *LevelAttemptFinished) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *LevelAttemptFinished) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *LevelAttemptFinished) GetScoreStart() int32 {
	if x != nil {
		return x.ScoreStart
	}
	return 0
}

func (x *LevelAttemptFinished) GetScoreEnd() int32 {
	if x != nil {
		return x.ScoreEnd
	}
	return 0
}

func (x *LevelAttemptFinished) GetLivesStart() int32 {
	if x != nil {
		return x.LivesStart
	}
	return 0
}

func (x *LevelAttemptFinished) GetLivesEnd() int32 {
	if x != nil {
		return x.LivesEnd
	}
	return 0
}

func (x *LevelAttemptFinished) GetActiveTargetsStart() uint32 {
	if x != nil {
		return x.ActiveTargetsStart
	}
	return 0
}

func (x *LevelAttemptFinished) GetActiveTargetsEnd() uint32 {
	if x != nil {
		return x.ActiveTargetsEnd
	}
	return 0
}

func (x *LevelAttemptFinished) GetStartedUnixNanos() int64 {
	if x != nil {
		return x.StartedUnixNanos
	}
	return 0
}

func (x *LevelAttemptFinished) GetGameplayStartedUnixNanos() int64 {
	if x != nil {
		return x.GameplayStartedUnixNanos
	}
	return 0
}

func (x *LevelAttemptFinished) GetEndedUnixNanos() int64 {
	if x != nil {
		return x.EndedUnixNanos
	}
	return 0
}

func (x *LevelAttemptFinished) GetElapsedMillis() int64 {
	if x != nil {
		return x.ElapsedMillis
	}
	return 0
}

type DisplaySnapshot struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	CurrentGame              string                 `protobuf:"bytes,1,opt,name=current_game,json=currentGame,proto3" json:"current_game,omitempty"`
	Label                    string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Phase                    string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	PlayerCount              uint32                 `protobuf:"varint,4,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	Players                  []*DisplayPlayer       `protobuf:"bytes,5,rep,name=players,proto3" json:"players,omitempty"`
	Score                    int32                  `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	Lives                    int32                  `protobuf:"varint,7,opt,name=lives,proto3" json:"lives,omitempty"`
	StartedUnix              int64                  `protobuf:"varint,8,opt,name=started_unix,json=startedUnix,proto3" json:"started_unix,omitempty"`
	EndsUnix                 int64                  `protobuf:"varint,9,opt,name=ends_unix,json=endsUnix,proto3" json:"ends_unix,omitempty"`
	ElapsedMillis            int64                  `protobuf:"varint,10,opt,name=elapsed_millis,json=elapsedMillis,proto3" json:"elapsed_millis,omitempty"`
	RemainingMillis          int64                  `protobuf:"varint,11,opt,name=remaining_millis,json=remainingMillis,proto3" json:"remaining_millis,omitempty"`
	ActiveTargets            uint32                 `protobuf:"varint,12,opt,name=active_targets,json=activeTargets,proto3" json:"active_targets,omitempty"`
	AudioEnabled             bool                   `protobuf:"varint,13,opt,name=audio_enabled,json=audioEnabled,proto3" json:"audio_enabled,omitempty"`
	LastEventUnixNanos       int64                  `protobuf:"varint,14,opt,name=last_event_unix_nanos,json=lastEventUnixNanos,proto3" json:"last_event_unix_nanos,omitempty"`
	LastEventCue             string                 `protobuf:"bytes,15,opt,name=last_event_cue,json=lastEventCue,proto3" json:"last_event_cue,omitempty"`
	LastEventMessage         string                 `protobuf:"bytes,16,opt,name=last_event_message,json=lastEventMessage,proto3" json:"last_event_message,omitempty"`
	IntroRemainingMillis     int64                  `protobuf:"varint,17,opt,name=intro_remaining_millis,json=introRemainingMillis,proto3" json:"intro_remaining_millis,omitempty"`
	CountdownRemainingMillis int64                  `protobuf:"varint,18,opt,name=countdown_remaining_millis,json=countdownRemainingMillis,proto3" json:"countdown_remaining_millis,omitempty"`
	AudioMuted               bool                   `protobuf:"varint,19,opt,name=audio_muted,json=audioMuted,proto3" json:"audio_muted,omitempty"`
	Level                    string                 `protobuf:"bytes,20,opt,name=level,proto3" json:"level,omitempty"`
	Difficulty               string                 `protobuf:"bytes,21,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Success                  bool                   `protobuf:"varint,22,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DisplaySnapshot) Reset() {
	*x = DisplaySnapshot{}
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplaySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplaySnapshot) ProtoMessage() {}

func (x *DisplaySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplaySnapshot.ProtoReflect.Descriptor instead.
func (*DisplaySnapshot) Descriptor() ([]byte, []int) {
	return file_packages_contracts_gamepb_game_proto_rawDescGZIP(), []int{10}
}

func (x *DisplaySnapshot) GetCurrentGame() string {
	if x != nil {
		return x.CurrentGame
	}
	return ""
}

func (x *DisplaySnapshot) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DisplaySnapshot) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *DisplaySnapshot) GetPlayerCount() uint32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *DisplaySnapshot) GetPlayers() []*DisplayPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *DisplaySnapshot) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *DisplaySnapshot) GetLives() int32 {
	if x != nil {
		return x.Lives
	}
	return 0
}

func (x *DisplaySnapshot) GetStartedUnix() int64 {
	if x != nil {
		return x.StartedUnix
	}
	return 0
}

func (x *DisplaySnapshot) GetEndsUnix() int64 {
	if x != nil {
		return x.EndsUnix
	}
	return 0
}

func (x *DisplaySnapshot) GetElapsedMillis() int64 {
	if x != nil {
		return x.ElapsedMillis
	}
	return 0
}

func (x *DisplaySnapshot) GetRemainingMillis() int64 {
	if x != nil {
		return x.RemainingMillis
	}
	return 0
}

func (x *DisplaySnapshot) GetActiveTargets() uint32 {
	if x != nil {
		return x.ActiveTargets
	}
	return 0
}

func (x *DisplaySnapshot) GetAudioEnabled() bool {
	if x != nil {
		return x.AudioEnabled
	}
	return false
}

func (x *DisplaySnapshot) GetLastEventUnixNanos() int64 {
	if x != nil {
		return x.LastEventUnixNanos
	}
	return 0
}

func (x *DisplaySnapshot) GetLastEventCue() string {
	if x != nil {
		return x.LastEventCue
	}
	return ""
}

func (x *DisplaySnapshot) GetLastEventMessage() string {
	if x != nil {
		return x.LastEventMessage
	}
	return ""
}

func (x *DisplaySnapshot) GetIntroRemainingMillis() int64 {
	if x != nil {
		return x.IntroRemainingMillis
	}
	return 0
}

func (x *DisplaySnapshot) GetCountdownRemainingMillis() int64 {
	if x != nil {
		return x.CountdownRemainingMillis
	}
	return 0
}

func (x *DisplaySnapshot) GetAudioMuted() bool {
	if x != nil {
		return x.AudioMuted
	}
	return false
}

func (x *DisplaySnapshot) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *DisplaySnapshot) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *DisplaySnapshot) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DisplayPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Color         *Color                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	Lives         int32                  `protobuf:"varint,5,opt,name=lives,proto3" json:"lives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplayPlayer) Reset() {
	*x = DisplayPlayer{}
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayPlayer) ProtoMessage() {}

func (x *DisplayPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayPlayer.ProtoReflect.Descriptor instead.
func (*DisplayPlayer) Descriptor() ([]byte, []int) {
	return file_packages_contracts_gamepb_game_proto_rawDescGZIP(), []int{11}
}

func (x *DisplayPlayer) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DisplayPlayer) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DisplayPlayer) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *DisplayPlayer) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *DisplayPlayer) GetLives() int32 {
	if x != nil {
		return x.Lives
	}
	return 0
}

type Color struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             uint32                 `protobuf:"varint,1,opt,name=r,proto3" json:"r,omitempty"`
	G             uint32                 `protobuf:"varint,2,opt,name=g,proto3" json:"g,omitempty"`
	B             uint32                 `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Color) Reset() {
	*x = Color{}
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_gamepb_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_packages_contracts_gamepb_game_proto_rawDescGZIP(), []int{12}
}

func (x *Color) GetR() uint32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *Color) GetG() uint32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *Color) GetB() uint32 {
	if x != nil {
		return x.B
	}
	return 0
}

var File_packages_contracts_gamepb_game_proto protoreflect.FileDescriptor

const file_packages_contracts_gamepb_game_proto_rawDesc = "" +
	"\n" +
	"$packages/contracts/gamepb/game.proto\x12\x1bmotionlevels.engine.game.v1\"\x85\b\n" +
	"\x11GameSessionRecord\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x1d\n" +
	"\n" +
	"unix_nanos\x18\x03 \x01(\x03R\tunixNanos\x12(\n" +
	"\x10venue_session_id\x18\x04 \x01(\tR\x0evenueSessionId\x12V\n" +
	"\x0fsession_started\x18\n" +
	" \x01(\v2+.motionlevels.engine.game.v1.SessionStartedH\x00R\x0esessionStarted\x12P\n" +
	"\rsession_ended\x18\v \x01(\v2).motionlevels.engine.game.v1.SessionEndedH\x00R\fsessionEnded\x12V\n" +
	"\x0fapi_interaction\x18\f \x01(\v2+.motionlevels.engine.game.v1.ApiInteractionH\x00R\x0eapiInteraction\x12M\n" +
	"\fmenu_command\x18\r \x01(\v2(.motionlevels.engine.game.v1.MenuCommandH\x00R\vmenuCommand\x12S\n" +
	"\x0epressure_input\x18\x0e \x01(\v2*.motionlevels.engine.game.v1.PressureInputH\x00R\rpressureInput\x12G\n" +
	"\n" +
	"game_event\x18\x0f \x01(\v2&.motionlevels.engine.game.v1.GameEventH\x00R\tgameEvent\x12D\n" +
	"\taudio_cue\x18\x10 \x01(\v2%.motionlevels.engine.game.v1.AudioCueH\x00R\baudioCue\x12Y\n" +
	"\x10display_snapshot\x18\x11 \x01(\v2,.motionlevels.engine.game.v1.DisplaySnapshotH\x00R\x0fdisplaySnapshot\x12f\n" +
	"\x15level_attempt_started\x18\x12 \x01(\v20.motionlevels.engine.game.v1.LevelAttemptStartedH\x00R\x13levelAttemptStarted\x12i\n" +
	"\x16level_attempt_finished\x18\x13 \x01(\v21.motionlevels.engine.game.v1.LevelAttemptFinishedH\x00R\x14levelAttemptFinishedB\t\n" +
	"\apayload\"\xe9\x02\n" +
	"\x0eSessionStarted\x12\x12\n" +
	"\x04game\x18\x01 \x01(\tR\x04game\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12!\n" +
	"\fplayer_count\x18\x03 \x01(\rR\vplayerCount\x12\x19\n" +
	"\brng_seed\x18\x04 \x01(\x03R\arngSeed\x12,\n" +
	"\x12started_unix_nanos\x18\x05 \x01(\x03R\x10startedUnixNanos\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x06 \x01(\tR\n" +
	"difficulty\x12\x14\n" +
	"\x05level\x18\a \x01(\tR\x05level\x12\x1b\n" +
	"\tteam_name\x18\b \x01(\tR\bteamName\x12D\n" +
	"\aplayers\x18\t \x03(\v2*.motionlevels.engine.game.v1.DisplayPlayerR\aplayers\x12(\n" +
	"\x10venue_session_id\x18\n" +
	" \x01(\tR\x0evenueSessionId\"P\n" +
	"\fSessionEnded\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12(\n" +
	"\x10ended_unix_nanos\x18\x02 \x01(\x03R\x0eendedUnixNanos\"\x94\x01\n" +
	"\x0eApiInteraction\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1f\n" +
	"\vremote_addr\x18\x03 \x01(\tR\n" +
	"remoteAddr\x12\x1d\n" +
	"\n" +
	"unix_nanos\x18\x04 \x01(\x03R\tunixNanos\x12\x16\n" +
	"\x06status\x18\x05 \x01(\rR\x06status\"}\n" +
	"\vMenuCommand\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04game\x18\x02 \x01(\tR\x04game\x12!\n" +
	"\fplayer_count\x18\x03 \x01(\rR\vplayerCount\x12\x1d\n" +
	"\n" +
	"unix_nanos\x18\x04 \x01(\x03R\tunixNanos\"\xfb\x01\n" +
	"\rPressureInput\x12'\n" +
	"\x0fsource_sequence\x18\x01 \x01(\x04R\x0esourceSequence\x12\x1d\n" +
	"\n" +
	"unix_nanos\x18\x02 \x01(\x03R\tunixNanos\x12\f\n" +
	"\x01x\x18\x03 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\rR\x01y\x12\x18\n" +
	"\apressed\x18\x05 \x01(\bR\apressed\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"controller\x18\a \x01(\rR\n" +
	"controller\x12\x18\n" +
	"\achannel\x18\b \x01(\rR\achannel\x12\x1a\n" +
	"\bposition\x18\t \x01(\rR\bposition\"V\n" +
	"\tGameEvent\x12\x10\n" +
	"\x03cue\x18\x01 \x01(\tR\x03cue\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"unix_nanos\x18\x03 \x01(\x03R\tunixNanos\"e\n" +
	"\bAudioCue\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x10\n" +
	"\x03cue\x18\x02 \x01(\tR\x03cue\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x01R\x06volume\x12\x1d\n" +
	"\n" +
	"unix_nanos\x18\x04 \x01(\x03R\tunixNanos\"\xaa\x03\n" +
	"\x13LevelAttemptStarted\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\x12\n" +
	"\x04game\x18\x02 \x01(\tR\x04game\x12\x19\n" +
	"\blevel_id\x18\x03 \x01(\tR\alevelId\x12!\n" +
	"\flevel_number\x18\x04 \x01(\rR\vlevelNumber\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\tR\n" +
	"difficulty\x12!\n" +
	"\fplayer_count\x18\x06 \x01(\rR\vplayerCount\x12\x1f\n" +
	"\vlives_start\x18\a \x01(\x05R\n" +
	"livesStart\x12\x1f\n" +
	"\vscore_start\x18\b \x01(\x05R\n" +
	"scoreStart\x120\n" +
	"\x14active_targets_start\x18\t \x01(\rR\x12activeTargetsStart\x12,\n" +
	"\x12started_unix_nanos\x18\n" +
	" \x01(\x03R\x10startedUnixNanos\x12=\n" +
	"\x1bgameplay_started_unix_nanos\x18\v \x01(\x03R\x18gameplayStartedUnixNanos\"\xd9\x04\n" +
	"\x14LevelAttemptFinished\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\x12\n" +
	"\x04game\x18\x02 \x01(\tR\x04game\x12\x19\n" +
	"\blevel_id\x18\x03 \x01(\tR\alevelId\x12!\n" +
	"\flevel_number\x18\x04 \x01(\rR\vlevelNumber\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\tR\n" +
	"difficulty\x12\x16\n" +
	"\x06result\x18\x06 \x01(\tR\x06result\x12\x1f\n" +
	"\vscore_start\x18\a \x01(\x05R\n" +
	"scoreStart\x12\x1b\n" +
	"\tscore_end\x18\b \x01(\x05R\bscoreEnd\x12\x1f\n" +
	"\vlives_start\x18\t \x01(\x05R\n" +
	"livesStart\x12\x1b\n" +
	"\tlives_end\x18\n" +
	" \x01(\x05R\blivesEnd\x120\n" +
	"\x14active_targets_start\x18\v \x01(\rR\x12activeTargetsStart\x12,\n" +
	"\x12active_targets_end\x18\f \x01(\rR\x10activeTargetsEnd\x12,\n" +
	"\x12started_unix_nanos\x18\r \x01(\x03R\x10startedUnixNanos\x12=\n" +
	"\x1bgameplay_started_unix_nanos\x18\x0e \x01(\x03R\x18gameplayStartedUnixNanos\x12(\n" +
	"\x10ended_unix_nanos\x18\x0f \x01(\x03R\x0eendedUnixNanos\x12%\n" +
	"\x0eelapsed_millis\x18\x10 \x01(\x03R\relapsedMillis\"\xbf\x06\n" +
	"\x0fDisplaySnapshot\x12!\n" +
	"\fcurrent_game\x18\x01 \x01(\tR\vcurrentGame\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12!\n" +
	"\fplayer_count\x18\x04 \x01(\rR\vplayerCount\x12D\n" +
	"\aplayers\x18\x05 \x03(\v2*.motionlevels.engine.game.v1.DisplayPlayerR\aplayers\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x05R\x05score\x12\x14\n" +
	"\x05lives\x18\a \x01(\x05R\x05lives\x12!\n" +
	"\fstarted_unix\x18\b \x01(\x03R\vstartedUnix\x12\x1b\n" +
	"\tends_unix\x18\t \x01(\x03R\bendsUnix\x12%\n" +
	"\x0eelapsed_millis\x18\n" +
	" \x01(\x03R\relapsedMillis\x12)\n" +
	"\x10remaining_millis\x18\v \x01(\x03R\x0fremainingMillis\x12%\n" +
	"\x0eactive_targets\x18\f \x01(\rR\ractiveTargets\x12#\n" +
	"\raudio_enabled\x18\r \x01(\bR\faudioEnabled\x121\n" +
	"\x15last_event_unix_nanos\x18\x0e \x01(\x03R\x12lastEventUnixNanos\x12$\n" +
	"\x0elast_event_cue\x18\x0f \x01(\tR\flastEventCue\x12,\n" +
	"\x12last_event_message\x18\x10 \x01(\tR\x10lastEventMessage\x124\n" +
	"\x16intro_remaining_millis\x18\x11 \x01(\x03R\x14introRemainingMillis\x12<\n" +
	"\x1acountdown_remaining_millis\x18\x12 \x01(\x03R\x18countdownRemainingMillis\x12\x1f\n" +
	"\vaudio_muted\x18\x13 \x01(\bR\n" +
	"audioMuted\x12\x14\n" +
	"\x05level\x18\x14 \x01(\tR\x05level\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x15 \x01(\tR\n" +
	"difficulty\x12\x18\n" +
	"\asuccess\x18\x16 \x01(\bR\asuccess\"\xa1\x01\n" +
	"\rDisplayPlayer\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x128\n" +
	"\x05color\x18\x03 \x01(\v2\".motionlevels.engine.game.v1.ColorR\x05color\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x14\n" +
	"\x05lives\x18\x05 \x01(\x05R\x05lives\"1\n" +
	"\x05Color\x12\f\n" +
	"\x01r\x18\x01 \x01(\rR\x01r\x12\f\n" +
	"\x01g\x18\x02 \x01(\rR\x01g\x12\f\n" +
	"\x01b\x18\x03 \x01(\rR\x01bB:Z8github.com/lobis/motion-levels/packages/contracts/gamepbb\x06proto3"

var (
	file_packages_contracts_gamepb_game_proto_rawDescOnce sync.Once
	file_packages_contracts_gamepb_game_proto_rawDescData []byte
)

func file_packages_contracts_gamepb_game_proto_rawDescGZIP() []byte {
	file_packages_contracts_gamepb_game_proto_rawDescOnce.Do(func() {
		file_packages_contracts_gamepb_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_contracts_gamepb_game_proto_rawDesc), len(file_packages_contracts_gamepb_game_proto_rawDesc)))
	})
	return file_packages_contracts_gamepb_game_proto_rawDescData
}

var file_packages_contracts_gamepb_game_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_packages_contracts_gamepb_game_proto_goTypes = []any{
	(*GameSessionRecord)(nil),    // 0: motionlevels.engine.game.v1.GameSessionRecord
	(*SessionStarted)(nil),       // 1: motionlevels.engine.game.v1.SessionStarted
	(*SessionEnded)(nil),         // 2: motionlevels.engine.game.v1.SessionEnded
	(*ApiInteraction)(nil),       // 3: motionlevels.engine.game.v1.ApiInteraction
	(*MenuCommand)(nil),          // 4: motionlevels.engine.game.v1.MenuCommand
	(*PressureInput)(nil),        // 5: motionlevels.engine.game.v1.PressureInput
	(*GameEvent)(nil),            // 6: motionlevels.engine.game.v1.GameEvent
	(*AudioCue)(nil),             // 7: motionlevels.engine.game.v1.AudioCue
	(*LevelAttemptStarted)(nil),  // 8: motionlevels.engine.game.v1.LevelAttemptStarted
	(*LevelAttemptFinished)(nil), // 9: motionlevels.engine.game.v1.LevelAttemptFinished
	(*DisplaySnapshot)(nil),      // 10: motionlevels.engine.game.v1.DisplaySnapshot
	(*DisplayPlayer)(nil),        // 11: motionlevels.engine.game.v1.DisplayPlayer
	(*Color)(nil),                // 12: motionlevels.engine.game.v1.Color
}
var file_packages_contracts_gamepb_game_proto_depIdxs = []int32{
	1,  // 0: motionlevels.engine.game.v1.GameSessionRecord.session_started:type_name -> motionlevels.engine.game.v1.SessionStarted
	2,  // 1: motionlevels.engine.game.v1.GameSessionRecord.session_ended:type_name -> motionlevels.engine.game.v1.SessionEnded
	3,  // 2: motionlevels.engine.game.v1.GameSessionRecord.api_interaction:type_name -> motionlevels.engine.game.v1.ApiInteraction
	4,  // 3: motionlevels.engine.game.v1.GameSessionRecord.menu_command:type_name -> motionlevels.engine.game.v1.MenuCommand
	5,  // 4: motionlevels.engine.game.v1.GameSessionRecord.pressure_input:type_name -> motionlevels.engine.game.v1.PressureInput
	6,  // 5: motionlevels.engine.game.v1.GameSessionRecord.game_event:type_name -> motionlevels.engine.game.v1.GameEvent
	7,  // 6: motionlevels.engine.game.v1.GameSessionRecord.audio_cue:type_name -> motionlevels.engine.game.v1.AudioCue
	10, // 7: motionlevels.engine.game.v1.GameSessionRecord.display_snapshot:type_name -> motionlevels.engine.game.v1.DisplaySnapshot
	8,  // 8: motionlevels.engine.game.v1.GameSessionRecord.level_attempt_started:type_name -> motionlevels.engine.game.v1.LevelAttemptStarted
	9,  // 9: motionlevels.engine.game.v1.GameSessionRecord.level_attempt_finished:type_name -> motionlevels.engine.game.v1.LevelAttemptFinished
	11, // 10: motionlevels.engine.game.v1.SessionStarted.players:type_name -> motionlevels.engine.game.v1.DisplayPlayer
	11, // 11: motionlevels.engine.game.v1.DisplaySnapshot.players:type_name -> motionlevels.engine.game.v1.DisplayPlayer
	12, // 12: motionlevels.engine.game.v1.DisplayPlayer.color:type_name -> motionlevels.engine.game.v1.Color
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_packages_contracts_gamepb_game_proto_init() }
func file_packages_contracts_gamepb_game_proto_init() {
	if File_packages_contracts_gamepb_game_proto != nil {
		return
	}
	file_packages_contracts_gamepb_game_proto_msgTypes[0].OneofWrappers = []any{
		(*GameSessionRecord_SessionStarted)(nil),
		(*GameSessionRecord_SessionEnded)(nil),
		(*GameSessionRecord_ApiInteraction)(nil),
		(*GameSessionRecord_MenuCommand)(nil),
		(*GameSessionRecord_PressureInput)(nil),
		(*GameSessionRecord_GameEvent)(nil),
		(*GameSessionRecord_AudioCue)(nil),
		(*GameSessionRecord_DisplaySnapshot)(nil),
		(*GameSessionRecord_LevelAttemptStarted)(nil),
		(*GameSessionRecord_LevelAttemptFinished)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_contracts_gamepb_game_proto_rawDesc), len(file_packages_contracts_gamepb_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packages_contracts_gamepb_game_proto_goTypes,
		DependencyIndexes: file_packages_contracts_gamepb_game_proto_depIdxs,
		MessageInfos:      file_packages_contracts_gamepb_game_proto_msgTypes,
	}.Build()
	File_packages_contracts_gamepb_game_proto = out.File
	file_packages_contracts_gamepb_game_proto_goTypes = nil
	file_packages_contracts_gamepb_game_proto_depIdxs = nil
}
