// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: packages/contracts/inputpb/input.proto

package inputpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PressureEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	UnixNanos     int64                  `protobuf:"varint,2,opt,name=unix_nanos,json=unixNanos,proto3" json:"unix_nanos,omitempty"`
	X             uint32                 `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint32                 `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Pressed       bool                   `protobuf:"varint,5,opt,name=pressed,proto3" json:"pressed,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Controller    uint32                 `protobuf:"varint,7,opt,name=controller,proto3" json:"controller,omitempty"`
	Channel       uint32                 `protobuf:"varint,8,opt,name=channel,proto3" json:"channel,omitempty"`
	Position      uint32                 `protobuf:"varint,9,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PressureEvent) Reset() {
	*x = PressureEvent{}
	mi := &file_packages_contracts_inputpb_input_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PressureEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PressureEvent) ProtoMessage() {}

func (x *PressureEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_inputpb_input_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PressureEvent.ProtoReflect.Descriptor instead.
func (*PressureEvent) Descriptor() ([]byte, []int) {
	return file_packages_contracts_inputpb_input_proto_rawDescGZIP(), []int{0}
}

func (x *PressureEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PressureEvent) GetUnixNanos() int64 {
	if x != nil {
		return x.UnixNanos
	}
	return 0
}

func (x *PressureEvent) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PressureEvent) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PressureEvent) GetPressed() bool {
	if x != nil {
		return x.Pressed
	}
	return false
}

func (x *PressureEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PressureEvent) GetController() uint32 {
	if x != nil {
		return x.Controller
	}
	return 0
}

func (x *PressureEvent) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *PressureEvent) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

var File_packages_contracts_inputpb_input_proto protoreflect.FileDescriptor

const file_packages_contracts_inputpb_input_proto_rawDesc = "" +
	"\n" +
	"&packages/contracts/inputpb/input.proto\x12\x1cmotionlevels.engine.input.v1\"\xee\x01\n" +
	"\rPressureEvent\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x1d\n" +
	"\n" +
	"unix_nanos\x18\x02 \x01(\x03R\tunixNanos\x12\f\n" +
	"\x01x\x18\x03 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\rR\x01y\x12\x18\n" +
	"\apressed\x18\x05 \x01(\bR\apressed\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"controller\x18\a \x01(\rR\n" +
	"controller\x12\x18\n" +
	"\achannel\x18\b \x01(\rR\achannel\x12\x1a\n" +
	"\bposition\x18\t \x01(\rR\bpositionB;Z9github.com/lobis/motion-levels/packages/contracts/inputpbb\x06proto3"

var (
	file_packages_contracts_inputpb_input_proto_rawDescOnce sync.Once
	file_packages_contracts_inputpb_input_proto_rawDescData []byte
)

func file_packages_contracts_inputpb_input_proto_rawDescGZIP() []byte {
	file_packages_contracts_inputpb_input_proto_rawDescOnce.Do(func() {
		file_packages_contracts_inputpb_input_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_contracts_inputpb_input_proto_rawDesc), len(file_packages_contracts_inputpb_input_proto_rawDesc)))
	})
	return file_packages_contracts_inputpb_input_proto_rawDescData
}

var file_packages_contracts_inputpb_input_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packages_contracts_inputpb_input_proto_goTypes = []any{
	(*PressureEvent)(nil), // 0: motionlevels.engine.input.v1.PressureEvent
}
var file_packages_contracts_inputpb_input_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packages_contracts_inputpb_input_proto_init() }
func file_packages_contracts_inputpb_input_proto_init() {
	if File_packages_contracts_inputpb_input_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_contracts_inputpb_input_proto_rawDesc), len(file_packages_contracts_inputpb_input_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packages_contracts_inputpb_input_proto_goTypes,
		DependencyIndexes: file_packages_contracts_inputpb_input_proto_depIdxs,
		MessageInfos:      file_packages_contracts_inputpb_input_proto_msgTypes,
	}.Build()
	File_packages_contracts_inputpb_input_proto = out.File
	file_packages_contracts_inputpb_input_proto_goTypes = nil
	file_packages_contracts_inputpb_input_proto_depIdxs = nil
}
