all:
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
    motion_levels_go_version: "1.26.3"
    motion_levels_go_bin: /usr/local/go/bin/go
    motion_levels_remote_root: /opt/motion-levels/rebuild
    motion_levels_remote_src: /opt/motion-levels/rebuild/src
  children:
    motion_levels_dev:
      hosts:
        motionlevels-dev:
          ansible_host: 100.119.0.4
          motion_levels_repo_root: /opt/motion-levels/repo
          motion_levels_platform_health_url: http://10.137.25.241:3000/api/sessions
          motion_levels_platform_bind_ip: 10.137.25.241
          motion_levels_platform_url: https://platform.motionlevels.obis.dev
    motion_levels_website:
      hosts:
        motionlevels-website:
          ansible_host: 100.103.216.65
          motion_levels_repo_root: /opt/motion-levels/repo
          motion_levels_website_health_url: http://127.0.0.1:3000
          motion_levels_website_url: https://website.motionlevels.obis.dev
          motion_levels_website_cms_health_url: http://127.0.0.1:8055/admin/login
          motion_levels_website_cms_url: https://cms.motionlevels.obis.dev
    motion_levels_venues:
      hosts:
        motionlevels-1:
          ansible_host: 100.76.156.89
          motion_levels_hostname: motionlevels-1
        motionlevels-cloud-1:
          ansible_host: 100.94.69.53
          motion_levels_hostname: motionlevels-cloud-1
